# Generated by Django 6.0.1 on 2026-02-11 11:09

import DOSPORTAL.models.measurements
import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.db.models.deletion
import markdownx.models
import martor.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Airports',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField()),
                ('code_iata', models.CharField(null=True, unique=True)),
                ('code_icao', models.CharField(null=True, unique=True)),
                ('lat', models.FloatField(null=True)),
                ('lon', models.FloatField(null=True)),
                ('alt', models.FloatField(null=True)),
                ('municipality', models.CharField(null=True)),
                ('web', models.CharField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CARImodel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('data', models.JSONField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DetectorManufacturer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('url', models.URLField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MeasurementCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='measurement name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('data_policy', models.CharField(choices=[('PR', 'Private'), ('PU', 'Public'), ('NV', 'Non-public')], default='PU', max_length=2)),
                ('can_users_change_policy', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Trajectory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DetectorCalib',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(verbose_name='Calibration name')),
                ('description', models.TextField(verbose_name='Description of calibration status')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('coef0', models.FloatField(default=0.0, verbose_name='Coefficient 0 (offset)')),
                ('coef1', models.FloatField(default=1, verbose_name='Coefficient 1, (linear)')),
                ('coef2', models.FloatField(default=0.0, verbose_name='Coefficient 2, (quadratic)')),
                ('author', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='calibrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Detector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('sn', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=150, verbose_name='Detector name')),
                ('manufactured_date', models.DateField(blank=True, help_text='Date when detector was manufactured', null=True, verbose_name='Manufactured date')),
                ('data', models.JSONField(blank=True, default=dict, help_text='Detector metadata, used for advanced data processing and maintaining', verbose_name='Detector metadata')),
                ('calib', models.ManyToManyField(blank=True, help_text='Detector calibration', related_name='detectors', to='DOSPORTAL.detectorcalib')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DetectorLogbook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('text', models.TextField(help_text='Detailed description of activity made on the detector.', verbose_name='Logbook text')),
                ('public', models.BooleanField(default=True, help_text='Private logbook will be visible for maintainers of detector and for dosportal admins.', verbose_name='Wish to be visible to everyone?')),
                ('entry_type', models.CharField(choices=[('reset', 'Reset'), ('sync', 'Sync'), ('maintenance', 'Maintenance'), ('note', 'Note'), ('location_update', 'Location update'), ('calibration', 'Calibration'), ('other', 'Other')], default='note', help_text='Category of the logbook entry.', max_length=30)),
                ('source', models.CharField(choices=[('web', 'Web'), ('api', 'API'), ('qr', 'QR'), ('auto', 'Automatic'), ('other', 'Other')], default='web', help_text='Origin of the logbook entry.', max_length=20)),
                ('latitude', models.FloatField(blank=True, help_text='GPS latitude of the location', null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, help_text='GPS longitude of the location', null=True, verbose_name='Longitude')),
                ('altitude', models.FloatField(blank=True, help_text='Altitude of the location in meters', null=True, verbose_name='Altitude')),
                ('location_text', models.CharField(blank=True, help_text='Location description in text format (e.g., address)', max_length=255, null=True, verbose_name='Location (text)')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('detector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logbook', to='DOSPORTAL.detector')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_logbook_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='DetectorType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('image', models.ImageField(blank=True, help_text='Detector image', null=True, upload_to='detector_images', verbose_name='Detector image')),
                ('url', models.URLField(blank=True, null=True)),
                ('description', markdownx.models.MarkdownxField(blank=True, help_text='Detector description', verbose_name='Detector description')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DOSPORTAL.detectormanufacturer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='detector',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DOSPORTAL.detectortype'),
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('file_type', models.CharField(choices=[('log', 'Log file'), ('trajectory', 'Trajectory'), ('document', 'Document'), ('image', 'Image'), ('other', 'Other')], default='log', max_length=32)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('size', models.BigIntegerField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_files', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_files', to='DOSPORTAL.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('flight_number', models.CharField()),
                ('departure_time', models.DateTimeField(null=True, verbose_name='Scheduled departure time')),
                ('trajectory_file', models.FileField(upload_to=DOSPORTAL.models.measurements.Flight.user_directory_path, verbose_name='Trajectory log')),
                ('cari', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DOSPORTAL.carimodel')),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landing', to='DOSPORTAL.airports')),
                ('takeoff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='takeoff', to='DOSPORTAL.airports')),
            ],
            options={
                'unique_together': {('flight_number', 'departure_time')},
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('time_start', models.DateTimeField(blank=True, null=True, verbose_name='Measurement beginning time')),
                ('time_end', models.DateTimeField(blank=True, null=True, verbose_name='Measurement beginning time')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Time of creation')),
                ('name', models.CharField(max_length=150, verbose_name='measurement name')),
                ('description', martor.models.MartorField(blank=True, verbose_name='Measurement description')),
                ('public', models.BooleanField(default=True, verbose_name='Will be data publicly available')),
                ('measurement_type', models.CharField(choices=[('D', 'Debug measurement'), ('S', 'Static measurement'), ('M', 'Mobile measurement (ground)'), ('C', 'Civil airborne measurement'), ('A', 'Special airborne measurement')], default='S', help_text='Type of measurement', verbose_name='Certain measurement type, enum')),
                ('base_location_lat', models.FloatField(blank=True, default=None, null=True)),
                ('base_location_lon', models.FloatField(blank=True, default=None, null=True)),
                ('base_location_alt', models.FloatField(blank=True, default=None, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to=settings.AUTH_USER_MODEL)),
                ('files', models.ManyToManyField(blank=True, help_text='Files (logs, trajectories, docs, etc.) associated with this measurement.', related_name='measurements', to='DOSPORTAL.file')),
                ('flight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='measurement', to='DOSPORTAL.flight', verbose_name='Reference na objekt s informacemi o letu')),
                ('campaings', models.ManyToManyField(blank=True, related_name='Campaigns', to='DOSPORTAL.measurementcampaign')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MeasurementDataFlight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='DOSPORTAL.flight')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='detector',
            name='access',
            field=models.ManyToManyField(blank=True, related_name='detector_access', to='DOSPORTAL.organization'),
        ),
        migrations.AddField(
            model_name='detector',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='detectors', to='DOSPORTAL.organization'),
        ),
        migrations.CreateModel(
            name='OrganizationInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(help_text='SHA256 hex digest of the invite token', max_length=64, unique=True)),
                ('user_type', models.CharField(choices=[('ME', 'Member'), ('AD', 'Admin')], default='ME', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invites', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='DOSPORTAL.organization')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_invites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('ME', 'Member'), ('AD', 'Admin'), ('OW', 'Owner')], default='ME', max_length=2)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_organizations', to='DOSPORTAL.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'organization')},
            },
        ),
        migrations.AddField(
            model_name='organization',
            name='users',
            field=models.ManyToManyField(related_name='organizations', through='DOSPORTAL.OrganizationUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default_user_profileimage.jpg', upload_to='profile_pics')),
                ('web', models.URLField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrajectoryPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(blank=True, null=True, verbose_name='Point timestamp')),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('trajectory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='DOSPORTAL.trajectory')),
            ],
        ),
        migrations.CreateModel(
            name='SpectrumData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('spectrum', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True)),
                ('integration', models.FloatField(blank=True, help_text='Duration of last exposition', null=True, verbose_name='Integration time')),
                ('particles', models.IntegerField(blank=True, help_text='Particles detected in the spectrum', null=True, verbose_name='Particles')),
                ('time', models.DurationField(help_text='Time difference from the start of the measurement', null=True, verbose_name='Time difference')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spectrum_data', to='DOSPORTAL.file', verbose_name='File')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spectrum_data', to='DOSPORTAL.trajectorypoint')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
