# Generated by Django 6.0.1 on 2026-02-13 12:05

import datetime
import django.db.models.deletion
import django.utils.timezone
import markdownx.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOSPORTAL', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='uploaded_by',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='file',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='file',
            name='name',
        ),
        migrations.AddField(
            model_name='file',
            name='filename',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='descriptive filename'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='source_type',
            field=models.CharField(choices=[('uploaded', 'Uploaded by user'), ('generated', 'Generated by system')], default='uploaded', max_length=16),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to='uploads/%Y/%m/%d/', verbose_name='storage (s3) pointer'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_type',
            field=models.CharField(choices=[('log', 'Log file'), ('trajectory', 'Trajectory'), ('document', 'Document'), ('image', 'Image'), ('other', 'Other'), ('parquet', 'Parquet')], default='log', max_length=32),
        ),
        migrations.CreateModel(
            name='SpectralRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(default='Record', help_text='Name of this record. Short and simple description of record.', max_length=80, null=True, verbose_name='Record name')),
                ('description', markdownx.models.MarkdownxField(blank=True, help_text='Description of the record', verbose_name='Description')),
                ('time_tracked', models.BooleanField(default=False, help_text='Tick this box if the record is dependent on absolute time. When you need align record to real time.', verbose_name='Is time tracked?')),
                ('time_internal_start', models.FloatField(blank=True, default=0, help_text='System time of record start', null=True, verbose_name='Internal time start')),
                ('time_start', models.DateTimeField(blank=True, default=datetime.datetime(2000, 1, 1, 0, 0), help_text="When 'time is tracked', you can set start time of the record beginning. ", null=True, verbose_name='Measurement beginning time')),
                ('time_of_interest_start', models.FloatField(blank=True, default=None, null=True, verbose_name='Time of interest start')),
                ('time_of_interest_end', models.FloatField(blank=True, default=None, null=True, verbose_name='Time of interest end')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Time of creation')),
                ('record_duration', models.DurationField(help_text='Duration of record', null=True, verbose_name='Record duration')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='record metadata, used for advanced data processing and maintaining', verbose_name='record_metadata')),
                ('processing_status', models.CharField(choices=[('pending', 'Pending processing'), ('processing', 'Processing in progress'), ('completed', 'Processing completed'), ('failed', 'Processing failed')], default='pending', help_text='Status of async background processing', max_length=16)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('calib', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='DOSPORTAL.detectorcalib')),
                ('detector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='DOSPORTAL.detector')),
                ('owner', models.ForeignKey(choices=[('PR', 'Private'), ('PU', 'Public'), ('NV', 'Non-public')], default='PU', help_text='Data policy of this record. Field can be overridden depending on the settings of the owning organization.', max_length=2, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='records_owning', to='DOSPORTAL.organization')),
                ('raw_file', models.ForeignKey(blank=True, help_text='Uploaded sourcec File', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spectral_records_raw', to='DOSPORTAL.file')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpectralRecordArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('artifact_type', models.CharField(choices=[('spectral', 'Processed log file into spectral file (Parquet)'), ('hist', 'Histogram data')], help_text='Type of artifact (e.g. histogram, processed spectral logs, ...)', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Time when the artifact was created')),
                ('artifact', models.ForeignKey(help_text='Processed file (artifact) referencing File', on_delete=django.db.models.deletion.CASCADE, related_name='spectral_artifacts', to='DOSPORTAL.file')),
                ('spectral_record', models.ForeignKey(help_text='Reference to SpectralRecord to which this artifact belongs', on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='DOSPORTAL.spectralrecord')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
