# Generated by Django 6.0.2 on 2026-02-18 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOSPORTAL', '0002_rename_uploaded_by_file_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='campaings',
        ),
        migrations.AddField(
            model_name='measurement',
            name='campaigns',
            field=models.ManyToManyField(blank=True, help_text='Measurement campaigns this measurement belongs to.', related_name='campaigns', to='DOSPORTAL.measurementcampaign', verbose_name='Campaigns'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='records',
            field=models.ManyToManyField(blank=True, help_text='Spectral records associated with this measurement.', related_name='measurements', to='DOSPORTAL.spectralrecord', verbose_name='Spectral records'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='files',
            field=models.ManyToManyField(blank=True, help_text='Additional files (documents, images, certificates) not associated with specific records.', related_name='measurements', to='DOSPORTAL.file', verbose_name='Additional files'),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='flight',
            field=models.ForeignKey(blank=True, help_text='Flight information associated with this measurement.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='measurement', to='DOSPORTAL.flight', verbose_name='Flight'),
        ),
        migrations.AlterField(
            model_name='spectralrecordartifact',
            name='artifact_type',
            field=models.CharField(choices=[('spectral', 'Processed log file into spectral file (Parquet)')], help_text='Type of artifact (e.g. histogram, processed spectral logs, ...)', max_length=16),
        ),
    ]
