# Generated by Django 6.0.2 on 2026-02-18 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOSPORTAL', '0003_remove_measurement_campaings_measurement_campaigns_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Organization that owns this measurement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measurements', to='DOSPORTAL.organization', verbose_name='Owner organization'),
        ),
    ]
