# Generated by Django 6.0.2 on 2026-02-18 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOSPORTAL', '0004_measurement_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spectralrecord',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Organization that owns this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records_owning', to='DOSPORTAL.organization'),
        ),
    ]
