# Generated by Django 6.0.2 on 2026-02-20 14:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOSPORTAL', '0005_alter_spectralrecord_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementSegment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('time_from', models.DateTimeField(blank=True, null=True, verbose_name='Segment start time')),
                ('time_to', models.DateTimeField(blank=True, null=True, verbose_name='Segment end time')),
                ('position', models.IntegerField(default=0, verbose_name='Position / order within measurement')),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='DOSPORTAL.measurement', verbose_name='Measurement')),
                ('spectral_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='DOSPORTAL.spectralrecord', verbose_name='Spectral record')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
