# Generated by Django 6.0.2 on 2026-02-20 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DOSPORTAL', '0006_measurementsegment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='records',
        ),
    ]
