# Generated by Django 6.0.2 on 2026-02-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOSPORTAL', '0008_detector_deleted_at_detector_deleted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detector',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
