# Generated by Django 6.0.2 on 2026-02-27 08:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOSPORTAL', '0009_detector_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation time')),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurement_artifacts', to='DOSPORTAL.file', verbose_name='Artifact file')),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='DOSPORTAL.measurement', verbose_name='Measurement')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
