# Generated by Django 6.0.2 on 2026-02-27 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOSPORTAL', '0010_measurementartifact'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementartifact',
            name='artifact_type',
            field=models.CharField(choices=[('spectral', 'Processed log file into spectral file (Parquet)')], default='spectral', max_length=50, verbose_name='Artifact type'),
        ),
    ]
