# Generated by Django 6.0.2 on 2026-02-27 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOSPORTAL', '0012_alter_measurementartifact_artifact_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pending processing'), ('processing', 'Processing in progress'), ('completed', 'Processing completed'), ('failed', 'Processing failed')], default='pending', help_text='Status of async background processing', max_length=16),
        ),
    ]
