# Generated by Django 6.0.2 on 2026-03-03 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOSPORTAL', '0013_measurement_processing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='detector',
            name='image',
            field=models.ImageField(blank=True, help_text='Photo of the detector', null=True, upload_to='detector_photos', verbose_name='Detector image'),
        ),
    ]
