/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * DOSPORTAL API
 * API Documentation for DOSPORTAL
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  File,
  FileUploadRequest,
  FilesListParams,
  PaginatedFileList
} from '.././model';





/**
 * List files accessible to the current user.
 */
export const filesList = (
    params?: FilesListParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PaginatedFileList>> => {
    
    
    return axios.default.get(
      `/api/files/`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getFilesListQueryKey = (params?: FilesListParams,) => {
    return [
    `/api/files/`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getFilesListQueryOptions = <TData = Awaited<ReturnType<typeof filesList>>, TError = AxiosError<unknown>>(params?: FilesListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof filesList>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFilesListQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof filesList>>> = ({ signal }) => filesList(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof filesList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FilesListQueryResult = NonNullable<Awaited<ReturnType<typeof filesList>>>
export type FilesListQueryError = AxiosError<unknown>


export function useFilesList<TData = Awaited<ReturnType<typeof filesList>>, TError = AxiosError<unknown>>(
 params: undefined |  FilesListParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof filesList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof filesList>>,
          TError,
          Awaited<ReturnType<typeof filesList>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFilesList<TData = Awaited<ReturnType<typeof filesList>>, TError = AxiosError<unknown>>(
 params?: FilesListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof filesList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof filesList>>,
          TError,
          Awaited<ReturnType<typeof filesList>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFilesList<TData = Awaited<ReturnType<typeof filesList>>, TError = AxiosError<unknown>>(
 params?: FilesListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof filesList>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useFilesList<TData = Awaited<ReturnType<typeof filesList>>, TError = AxiosError<unknown>>(
 params?: FilesListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof filesList>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFilesListQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Upload a file. Supply owner (org UUID) to assign to an organization (user must be admin/owner).
 */
export const filesCreate = (
    fileUploadRequest: FileUploadRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<File>> => {
    
    
    return axios.default.post(
      `/api/files/`,
      fileUploadRequest,options
    );
  }



export const getFilesCreateMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof filesCreate>>, TError,{data: FileUploadRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof filesCreate>>, TError,{data: FileUploadRequest}, TContext> => {

const mutationKey = ['filesCreate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof filesCreate>>, {data: FileUploadRequest}> = (props) => {
          const {data} = props ?? {};

          return  filesCreate(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type FilesCreateMutationResult = NonNullable<Awaited<ReturnType<typeof filesCreate>>>
    export type FilesCreateMutationBody = FileUploadRequest
    export type FilesCreateMutationError = AxiosError<unknown>

    export const useFilesCreate = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof filesCreate>>, TError,{data: FileUploadRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof filesCreate>>,
        TError,
        {data: FileUploadRequest},
        TContext
      > => {

      const mutationOptions = getFilesCreateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Get file detail by ID.
 */
export const filesRetrieve = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<File>> => {
    
    
    return axios.default.get(
      `/api/files/${id}/`,options
    );
  }




export const getFilesRetrieveQueryKey = (id?: string,) => {
    return [
    `/api/files/${id}/`
    ] as const;
    }

    
export const getFilesRetrieveQueryOptions = <TData = Awaited<ReturnType<typeof filesRetrieve>>, TError = AxiosError<unknown>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof filesRetrieve>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFilesRetrieveQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof filesRetrieve>>> = ({ signal }) => filesRetrieve(id, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof filesRetrieve>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FilesRetrieveQueryResult = NonNullable<Awaited<ReturnType<typeof filesRetrieve>>>
export type FilesRetrieveQueryError = AxiosError<unknown>


export function useFilesRetrieve<TData = Awaited<ReturnType<typeof filesRetrieve>>, TError = AxiosError<unknown>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof filesRetrieve>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof filesRetrieve>>,
          TError,
          Awaited<ReturnType<typeof filesRetrieve>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFilesRetrieve<TData = Awaited<ReturnType<typeof filesRetrieve>>, TError = AxiosError<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof filesRetrieve>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof filesRetrieve>>,
          TError,
          Awaited<ReturnType<typeof filesRetrieve>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFilesRetrieve<TData = Awaited<ReturnType<typeof filesRetrieve>>, TError = AxiosError<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof filesRetrieve>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useFilesRetrieve<TData = Awaited<ReturnType<typeof filesRetrieve>>, TError = AxiosError<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof filesRetrieve>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFilesRetrieveQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Soft-delete a file (org admin/owner only).
 */
export const filesDestroy = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.delete(
      `/api/files/${id}/`,options
    );
  }



export const getFilesDestroyMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof filesDestroy>>, TError,{id: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof filesDestroy>>, TError,{id: string}, TContext> => {

const mutationKey = ['filesDestroy'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof filesDestroy>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  filesDestroy(id,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type FilesDestroyMutationResult = NonNullable<Awaited<ReturnType<typeof filesDestroy>>>
    
    export type FilesDestroyMutationError = AxiosError<unknown>

    export const useFilesDestroy = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof filesDestroy>>, TError,{id: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof filesDestroy>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getFilesDestroyMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    