from .utils import UUIDMixin
from django.db import models
from ..models.organizations import Organization
from django.conf import settings


class File(UUIDMixin):
    FILE_TYPE_LOG = "log"
    FILE_TYPE_TRAJECTORY = "trajectory"
    FILE_TYPE_DOCUMENT = "document"
    FILE_TYPE_IMAGE = "image"
    FILE_TYPE_OTHER = "other"
    FILE_TYPE_PARQUET = "parquet"

    FILE_TYPES = (
        # Upload types (raw files)
        (FILE_TYPE_LOG, "Log file"),
        (FILE_TYPE_TRAJECTORY, "Trajectory"),
        (FILE_TYPE_DOCUMENT, "Document"),
        (FILE_TYPE_IMAGE, "Image"),
        (FILE_TYPE_OTHER, "Other"),
        # Artifact Types (processed filetypes)
        (FILE_TYPE_PARQUET, "Parquet")
    )
    FILE_SOURCE = (
        ("uploaded", "Uploaded by user"),
        ("generated", "Generated by system"),
    )

    filename = models.CharField(verbose_name="descriptive filename", max_length=200)
    file = models.FileField(verbose_name="storage (s3) pointer", upload_to="uploads/%Y/%m/%d/")
    
    file_type = models.CharField(max_length=32, choices=FILE_TYPES, default="log")
    source_type = models.CharField(max_length=16, choices=FILE_SOURCE, default="uploaded")

    metadata = models.JSONField(blank=True, default=dict)
    size = models.BigIntegerField(null=True, blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="uploaded_files",
    )

    owner = models.ForeignKey(
        Organization,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="owned_files",
    )

    def __str__(self):
        return f"File: {self.filename} ({self.file_type})"
    
    def save(self, *args, **kwargs):
        if self.file and not self.size:
            self.size = self.file.size
        super().save(*args, **kwargs)