/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * DOSPORTAL API
 * API Documentation for DOSPORTAL
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  OrganizationDetail,
  OrganizationDetailRequest,
  OrganizationsListParams,
  PaginatedOrganizationDetailList,
  PatchedOrganizationDetailRequest
} from '.././model';





/**
 * Get invite details by token (public, no authentication required).
 */
export const invitesRetrieve = (
    token: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.get(
      `/api/invites/${token}/`,options
    );
  }




export const getInvitesRetrieveQueryKey = (token?: string,) => {
    return [
    `/api/invites/${token}/`
    ] as const;
    }

    
export const getInvitesRetrieveQueryOptions = <TData = Awaited<ReturnType<typeof invitesRetrieve>>, TError = AxiosError<unknown>>(token: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof invitesRetrieve>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getInvitesRetrieveQueryKey(token);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof invitesRetrieve>>> = ({ signal }) => invitesRetrieve(token, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(token), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof invitesRetrieve>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type InvitesRetrieveQueryResult = NonNullable<Awaited<ReturnType<typeof invitesRetrieve>>>
export type InvitesRetrieveQueryError = AxiosError<unknown>


export function useInvitesRetrieve<TData = Awaited<ReturnType<typeof invitesRetrieve>>, TError = AxiosError<unknown>>(
 token: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof invitesRetrieve>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof invitesRetrieve>>,
          TError,
          Awaited<ReturnType<typeof invitesRetrieve>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useInvitesRetrieve<TData = Awaited<ReturnType<typeof invitesRetrieve>>, TError = AxiosError<unknown>>(
 token: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof invitesRetrieve>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof invitesRetrieve>>,
          TError,
          Awaited<ReturnType<typeof invitesRetrieve>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useInvitesRetrieve<TData = Awaited<ReturnType<typeof invitesRetrieve>>, TError = AxiosError<unknown>>(
 token: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof invitesRetrieve>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useInvitesRetrieve<TData = Awaited<ReturnType<typeof invitesRetrieve>>, TError = AxiosError<unknown>>(
 token: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof invitesRetrieve>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getInvitesRetrieveQueryOptions(token,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Accept an invite and join the organization. Requires authentication.
 */
export const invitesAcceptCreate = (
    token: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    
    
    return axios.default.post(
      `/api/invites/${token}/accept/`,undefined,options
    );
  }



export const getInvitesAcceptCreateMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof invitesAcceptCreate>>, TError,{token: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof invitesAcceptCreate>>, TError,{token: string}, TContext> => {

const mutationKey = ['invitesAcceptCreate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof invitesAcceptCreate>>, {token: string}> = (props) => {
          const {token} = props ?? {};

          return  invitesAcceptCreate(token,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type InvitesAcceptCreateMutationResult = NonNullable<Awaited<ReturnType<typeof invitesAcceptCreate>>>
    
    export type InvitesAcceptCreateMutationError = AxiosError<unknown>

    export const useInvitesAcceptCreate = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof invitesAcceptCreate>>, TError,{token: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof invitesAcceptCreate>>,
        TError,
        {token: string},
        TContext
      > => {

      const mutationOptions = getInvitesAcceptCreateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * List all organizations (any authenticated user).
 */
export const organizationsList = (
    params?: OrganizationsListParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PaginatedOrganizationDetailList>> => {
    
    
    return axios.default.get(
      `/api/organizations/`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getOrganizationsListQueryKey = (params?: OrganizationsListParams,) => {
    return [
    `/api/organizations/`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getOrganizationsListQueryOptions = <TData = Awaited<ReturnType<typeof organizationsList>>, TError = AxiosError<unknown>>(params?: OrganizationsListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof organizationsList>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getOrganizationsListQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof organizationsList>>> = ({ signal }) => organizationsList(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof organizationsList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type OrganizationsListQueryResult = NonNullable<Awaited<ReturnType<typeof organizationsList>>>
export type OrganizationsListQueryError = AxiosError<unknown>


export function useOrganizationsList<TData = Awaited<ReturnType<typeof organizationsList>>, TError = AxiosError<unknown>>(
 params: undefined |  OrganizationsListParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof organizationsList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof organizationsList>>,
          TError,
          Awaited<ReturnType<typeof organizationsList>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useOrganizationsList<TData = Awaited<ReturnType<typeof organizationsList>>, TError = AxiosError<unknown>>(
 params?: OrganizationsListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof organizationsList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof organizationsList>>,
          TError,
          Awaited<ReturnType<typeof organizationsList>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useOrganizationsList<TData = Awaited<ReturnType<typeof organizationsList>>, TError = AxiosError<unknown>>(
 params?: OrganizationsListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof organizationsList>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useOrganizationsList<TData = Awaited<ReturnType<typeof organizationsList>>, TError = AxiosError<unknown>>(
 params?: OrganizationsListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof organizationsList>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getOrganizationsListQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Create a new organization. The creator automatically becomes owner.
 */
export const organizationsCreate = (
    organizationDetailRequest: OrganizationDetailRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<OrganizationDetail>> => {
    
    
    return axios.default.post(
      `/api/organizations/`,
      organizationDetailRequest,options
    );
  }



export const getOrganizationsCreateMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof organizationsCreate>>, TError,{data: OrganizationDetailRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof organizationsCreate>>, TError,{data: OrganizationDetailRequest}, TContext> => {

const mutationKey = ['organizationsCreate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof organizationsCreate>>, {data: OrganizationDetailRequest}> = (props) => {
          const {data} = props ?? {};

          return  organizationsCreate(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type OrganizationsCreateMutationResult = NonNullable<Awaited<ReturnType<typeof organizationsCreate>>>
    export type OrganizationsCreateMutationBody = OrganizationDetailRequest
    export type OrganizationsCreateMutationError = AxiosError<unknown>

    export const useOrganizationsCreate = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof organizationsCreate>>, TError,{data: OrganizationDetailRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof organizationsCreate>>,
        TError,
        {data: OrganizationDetailRequest},
        TContext
      > => {

      const mutationOptions = getOrganizationsCreateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Get organization detail by ID.
 */
export const organizationsRetrieve = (
    orgId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<OrganizationDetail>> => {
    
    
    return axios.default.get(
      `/api/organizations/${orgId}/`,options
    );
  }




export const getOrganizationsRetrieveQueryKey = (orgId?: string,) => {
    return [
    `/api/organizations/${orgId}/`
    ] as const;
    }

    
export const getOrganizationsRetrieveQueryOptions = <TData = Awaited<ReturnType<typeof organizationsRetrieve>>, TError = AxiosError<unknown>>(orgId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof organizationsRetrieve>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getOrganizationsRetrieveQueryKey(orgId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof organizationsRetrieve>>> = ({ signal }) => organizationsRetrieve(orgId, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(orgId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof organizationsRetrieve>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type OrganizationsRetrieveQueryResult = NonNullable<Awaited<ReturnType<typeof organizationsRetrieve>>>
export type OrganizationsRetrieveQueryError = AxiosError<unknown>


export function useOrganizationsRetrieve<TData = Awaited<ReturnType<typeof organizationsRetrieve>>, TError = AxiosError<unknown>>(
 orgId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof organizationsRetrieve>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof organizationsRetrieve>>,
          TError,
          Awaited<ReturnType<typeof organizationsRetrieve>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useOrganizationsRetrieve<TData = Awaited<ReturnType<typeof organizationsRetrieve>>, TError = AxiosError<unknown>>(
 orgId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof organizationsRetrieve>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof organizationsRetrieve>>,
          TError,
          Awaited<ReturnType<typeof organizationsRetrieve>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useOrganizationsRetrieve<TData = Awaited<ReturnType<typeof organizationsRetrieve>>, TError = AxiosError<unknown>>(
 orgId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof organizationsRetrieve>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useOrganizationsRetrieve<TData = Awaited<ReturnType<typeof organizationsRetrieve>>, TError = AxiosError<unknown>>(
 orgId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof organizationsRetrieve>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getOrganizationsRetrieveQueryOptions(orgId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Update organization (owner/admin only).
 */
export const organizationsUpdate = (
    orgId: string,
    organizationDetailRequest: OrganizationDetailRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<OrganizationDetail>> => {
    
    
    return axios.default.put(
      `/api/organizations/${orgId}/`,
      organizationDetailRequest,options
    );
  }



export const getOrganizationsUpdateMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof organizationsUpdate>>, TError,{orgId: string;data: OrganizationDetailRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof organizationsUpdate>>, TError,{orgId: string;data: OrganizationDetailRequest}, TContext> => {

const mutationKey = ['organizationsUpdate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof organizationsUpdate>>, {orgId: string;data: OrganizationDetailRequest}> = (props) => {
          const {orgId,data} = props ?? {};

          return  organizationsUpdate(orgId,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type OrganizationsUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof organizationsUpdate>>>
    export type OrganizationsUpdateMutationBody = OrganizationDetailRequest
    export type OrganizationsUpdateMutationError = AxiosError<unknown>

    export const useOrganizationsUpdate = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof organizationsUpdate>>, TError,{orgId: string;data: OrganizationDetailRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof organizationsUpdate>>,
        TError,
        {orgId: string;data: OrganizationDetailRequest},
        TContext
      > => {

      const mutationOptions = getOrganizationsUpdateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Partially update organization (owner/admin only).
 */
export const organizationsPartialUpdate = (
    orgId: string,
    patchedOrganizationDetailRequest: PatchedOrganizationDetailRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<OrganizationDetail>> => {
    
    
    return axios.default.patch(
      `/api/organizations/${orgId}/`,
      patchedOrganizationDetailRequest,options
    );
  }



export const getOrganizationsPartialUpdateMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof organizationsPartialUpdate>>, TError,{orgId: string;data: PatchedOrganizationDetailRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof organizationsPartialUpdate>>, TError,{orgId: string;data: PatchedOrganizationDetailRequest}, TContext> => {

const mutationKey = ['organizationsPartialUpdate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof organizationsPartialUpdate>>, {orgId: string;data: PatchedOrganizationDetailRequest}> = (props) => {
          const {orgId,data} = props ?? {};

          return  organizationsPartialUpdate(orgId,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type OrganizationsPartialUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof organizationsPartialUpdate>>>
    export type OrganizationsPartialUpdateMutationBody = PatchedOrganizationDetailRequest
    export type OrganizationsPartialUpdateMutationError = AxiosError<unknown>

    export const useOrganizationsPartialUpdate = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof organizationsPartialUpdate>>, TError,{orgId: string;data: PatchedOrganizationDetailRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof organizationsPartialUpdate>>,
        TError,
        {orgId: string;data: PatchedOrganizationDetailRequest},
        TContext
      > => {

      const mutationOptions = getOrganizationsPartialUpdateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Soft-delete an organization (owner/admin only).
 */
export const organizationsDestroy = (
    orgId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.delete(
      `/api/organizations/${orgId}/`,options
    );
  }



export const getOrganizationsDestroyMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof organizationsDestroy>>, TError,{orgId: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof organizationsDestroy>>, TError,{orgId: string}, TContext> => {

const mutationKey = ['organizationsDestroy'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof organizationsDestroy>>, {orgId: string}> = (props) => {
          const {orgId} = props ?? {};

          return  organizationsDestroy(orgId,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type OrganizationsDestroyMutationResult = NonNullable<Awaited<ReturnType<typeof organizationsDestroy>>>
    
    export type OrganizationsDestroyMutationError = AxiosError<unknown>

    export const useOrganizationsDestroy = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof organizationsDestroy>>, TError,{orgId: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof organizationsDestroy>>,
        TError,
        {orgId: string},
        TContext
      > => {

      const mutationOptions = getOrganizationsDestroyMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * GET: List organization invites (admin/owner only). POST: Create a new invite (admin/owner only).
 */
export const organizationsInvitesRetrieve = (
    orgId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<OrganizationDetail>> => {
    
    
    return axios.default.get(
      `/api/organizations/${orgId}/invites/`,options
    );
  }




export const getOrganizationsInvitesRetrieveQueryKey = (orgId?: string,) => {
    return [
    `/api/organizations/${orgId}/invites/`
    ] as const;
    }

    
export const getOrganizationsInvitesRetrieveQueryOptions = <TData = Awaited<ReturnType<typeof organizationsInvitesRetrieve>>, TError = AxiosError<unknown>>(orgId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof organizationsInvitesRetrieve>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getOrganizationsInvitesRetrieveQueryKey(orgId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof organizationsInvitesRetrieve>>> = ({ signal }) => organizationsInvitesRetrieve(orgId, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(orgId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof organizationsInvitesRetrieve>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type OrganizationsInvitesRetrieveQueryResult = NonNullable<Awaited<ReturnType<typeof organizationsInvitesRetrieve>>>
export type OrganizationsInvitesRetrieveQueryError = AxiosError<unknown>


export function useOrganizationsInvitesRetrieve<TData = Awaited<ReturnType<typeof organizationsInvitesRetrieve>>, TError = AxiosError<unknown>>(
 orgId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof organizationsInvitesRetrieve>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof organizationsInvitesRetrieve>>,
          TError,
          Awaited<ReturnType<typeof organizationsInvitesRetrieve>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useOrganizationsInvitesRetrieve<TData = Awaited<ReturnType<typeof organizationsInvitesRetrieve>>, TError = AxiosError<unknown>>(
 orgId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof organizationsInvitesRetrieve>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof organizationsInvitesRetrieve>>,
          TError,
          Awaited<ReturnType<typeof organizationsInvitesRetrieve>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useOrganizationsInvitesRetrieve<TData = Awaited<ReturnType<typeof organizationsInvitesRetrieve>>, TError = AxiosError<unknown>>(
 orgId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof organizationsInvitesRetrieve>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useOrganizationsInvitesRetrieve<TData = Awaited<ReturnType<typeof organizationsInvitesRetrieve>>, TError = AxiosError<unknown>>(
 orgId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof organizationsInvitesRetrieve>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getOrganizationsInvitesRetrieveQueryOptions(orgId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * GET: List organization invites (admin/owner only). POST: Create a new invite (admin/owner only).
 */
export const organizationsInvitesCreate = (
    orgId: string,
    organizationDetailRequest: OrganizationDetailRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<OrganizationDetail>> => {
    
    
    return axios.default.post(
      `/api/organizations/${orgId}/invites/`,
      organizationDetailRequest,options
    );
  }



export const getOrganizationsInvitesCreateMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof organizationsInvitesCreate>>, TError,{orgId: string;data: OrganizationDetailRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof organizationsInvitesCreate>>, TError,{orgId: string;data: OrganizationDetailRequest}, TContext> => {

const mutationKey = ['organizationsInvitesCreate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof organizationsInvitesCreate>>, {orgId: string;data: OrganizationDetailRequest}> = (props) => {
          const {orgId,data} = props ?? {};

          return  organizationsInvitesCreate(orgId,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type OrganizationsInvitesCreateMutationResult = NonNullable<Awaited<ReturnType<typeof organizationsInvitesCreate>>>
    export type OrganizationsInvitesCreateMutationBody = OrganizationDetailRequest
    export type OrganizationsInvitesCreateMutationError = AxiosError<unknown>

    export const useOrganizationsInvitesCreate = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof organizationsInvitesCreate>>, TError,{orgId: string;data: OrganizationDetailRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof organizationsInvitesCreate>>,
        TError,
        {orgId: string;data: OrganizationDetailRequest},
        TContext
      > => {

      const mutationOptions = getOrganizationsInvitesCreateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Revoke an active invite by its UUID (admin/owner only).
 */
export const organizationsInvitesDestroy = (
    orgId: string,
    inviteId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.delete(
      `/api/organizations/${orgId}/invites/${inviteId}/`,options
    );
  }



export const getOrganizationsInvitesDestroyMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof organizationsInvitesDestroy>>, TError,{orgId: string;inviteId: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof organizationsInvitesDestroy>>, TError,{orgId: string;inviteId: string}, TContext> => {

const mutationKey = ['organizationsInvitesDestroy'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof organizationsInvitesDestroy>>, {orgId: string;inviteId: string}> = (props) => {
          const {orgId,inviteId} = props ?? {};

          return  organizationsInvitesDestroy(orgId,inviteId,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type OrganizationsInvitesDestroyMutationResult = NonNullable<Awaited<ReturnType<typeof organizationsInvitesDestroy>>>
    
    export type OrganizationsInvitesDestroyMutationError = AxiosError<unknown>

    export const useOrganizationsInvitesDestroy = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof organizationsInvitesDestroy>>, TError,{orgId: string;inviteId: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof organizationsInvitesDestroy>>,
        TError,
        {orgId: string;inviteId: string},
        TContext
      > => {

      const mutationOptions = getOrganizationsInvitesDestroyMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * GET: List all members. POST: Add a member (admin/owner only).
 */
export const organizationsMembersRetrieve = (
    orgId: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<OrganizationDetail>> => {
    
    
    return axios.default.get(
      `/api/organizations/${orgId}/members/`,options
    );
  }




export const getOrganizationsMembersRetrieveQueryKey = (orgId?: string,) => {
    return [
    `/api/organizations/${orgId}/members/`
    ] as const;
    }

    
export const getOrganizationsMembersRetrieveQueryOptions = <TData = Awaited<ReturnType<typeof organizationsMembersRetrieve>>, TError = AxiosError<unknown>>(orgId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof organizationsMembersRetrieve>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getOrganizationsMembersRetrieveQueryKey(orgId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof organizationsMembersRetrieve>>> = ({ signal }) => organizationsMembersRetrieve(orgId, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(orgId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof organizationsMembersRetrieve>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type OrganizationsMembersRetrieveQueryResult = NonNullable<Awaited<ReturnType<typeof organizationsMembersRetrieve>>>
export type OrganizationsMembersRetrieveQueryError = AxiosError<unknown>


export function useOrganizationsMembersRetrieve<TData = Awaited<ReturnType<typeof organizationsMembersRetrieve>>, TError = AxiosError<unknown>>(
 orgId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof organizationsMembersRetrieve>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof organizationsMembersRetrieve>>,
          TError,
          Awaited<ReturnType<typeof organizationsMembersRetrieve>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useOrganizationsMembersRetrieve<TData = Awaited<ReturnType<typeof organizationsMembersRetrieve>>, TError = AxiosError<unknown>>(
 orgId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof organizationsMembersRetrieve>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof organizationsMembersRetrieve>>,
          TError,
          Awaited<ReturnType<typeof organizationsMembersRetrieve>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useOrganizationsMembersRetrieve<TData = Awaited<ReturnType<typeof organizationsMembersRetrieve>>, TError = AxiosError<unknown>>(
 orgId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof organizationsMembersRetrieve>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useOrganizationsMembersRetrieve<TData = Awaited<ReturnType<typeof organizationsMembersRetrieve>>, TError = AxiosError<unknown>>(
 orgId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof organizationsMembersRetrieve>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getOrganizationsMembersRetrieveQueryOptions(orgId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * GET: List all members. POST: Add a member (admin/owner only).
 */
export const organizationsMembersCreate = (
    orgId: string,
    organizationDetailRequest: OrganizationDetailRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<OrganizationDetail>> => {
    
    
    return axios.default.post(
      `/api/organizations/${orgId}/members/`,
      organizationDetailRequest,options
    );
  }



export const getOrganizationsMembersCreateMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof organizationsMembersCreate>>, TError,{orgId: string;data: OrganizationDetailRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof organizationsMembersCreate>>, TError,{orgId: string;data: OrganizationDetailRequest}, TContext> => {

const mutationKey = ['organizationsMembersCreate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof organizationsMembersCreate>>, {orgId: string;data: OrganizationDetailRequest}> = (props) => {
          const {orgId,data} = props ?? {};

          return  organizationsMembersCreate(orgId,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type OrganizationsMembersCreateMutationResult = NonNullable<Awaited<ReturnType<typeof organizationsMembersCreate>>>
    export type OrganizationsMembersCreateMutationBody = OrganizationDetailRequest
    export type OrganizationsMembersCreateMutationError = AxiosError<unknown>

    export const useOrganizationsMembersCreate = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof organizationsMembersCreate>>, TError,{orgId: string;data: OrganizationDetailRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof organizationsMembersCreate>>,
        TError,
        {orgId: string;data: OrganizationDetailRequest},
        TContext
      > => {

      const mutationOptions = getOrganizationsMembersCreateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * PUT: Update a member's role (admin/owner only). DELETE: Remove a member.
 */
export const organizationsMembersUpdate = (
    orgId: string,
    username: string,
    organizationDetailRequest: OrganizationDetailRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<OrganizationDetail>> => {
    
    
    return axios.default.put(
      `/api/organizations/${orgId}/members/${username}/`,
      organizationDetailRequest,options
    );
  }



export const getOrganizationsMembersUpdateMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof organizationsMembersUpdate>>, TError,{orgId: string;username: string;data: OrganizationDetailRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof organizationsMembersUpdate>>, TError,{orgId: string;username: string;data: OrganizationDetailRequest}, TContext> => {

const mutationKey = ['organizationsMembersUpdate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof organizationsMembersUpdate>>, {orgId: string;username: string;data: OrganizationDetailRequest}> = (props) => {
          const {orgId,username,data} = props ?? {};

          return  organizationsMembersUpdate(orgId,username,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type OrganizationsMembersUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof organizationsMembersUpdate>>>
    export type OrganizationsMembersUpdateMutationBody = OrganizationDetailRequest
    export type OrganizationsMembersUpdateMutationError = AxiosError<unknown>

    export const useOrganizationsMembersUpdate = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof organizationsMembersUpdate>>, TError,{orgId: string;username: string;data: OrganizationDetailRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof organizationsMembersUpdate>>,
        TError,
        {orgId: string;username: string;data: OrganizationDetailRequest},
        TContext
      > => {

      const mutationOptions = getOrganizationsMembersUpdateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * PUT: Update a member's role (admin/owner only). DELETE: Remove a member.
 */
export const organizationsMembersDestroy = (
    orgId: string,
    username: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.delete(
      `/api/organizations/${orgId}/members/${username}/`,options
    );
  }



export const getOrganizationsMembersDestroyMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof organizationsMembersDestroy>>, TError,{orgId: string;username: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof organizationsMembersDestroy>>, TError,{orgId: string;username: string}, TContext> => {

const mutationKey = ['organizationsMembersDestroy'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof organizationsMembersDestroy>>, {orgId: string;username: string}> = (props) => {
          const {orgId,username} = props ?? {};

          return  organizationsMembersDestroy(orgId,username,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type OrganizationsMembersDestroyMutationResult = NonNullable<Awaited<ReturnType<typeof organizationsMembersDestroy>>>
    
    export type OrganizationsMembersDestroyMutationError = AxiosError<unknown>

    export const useOrganizationsMembersDestroy = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof organizationsMembersDestroy>>, TError,{orgId: string;username: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof organizationsMembersDestroy>>,
        TError,
        {orgId: string;username: string},
        TContext
      > => {

      const mutationOptions = getOrganizationsMembersDestroyMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    