/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * DOSPORTAL API
 * API Documentation for DOSPORTAL
 * OpenAPI spec version: 1.0.0
 */

export interface AirportRequest {
  /** @minLength 1 */
  name: string;
  /**
   * @minLength 1
   * @nullable
   */
  code_iata?: string | null;
  /**
   * @minLength 1
   * @nullable
   */
  code_icao?: string | null;
  /**
   * @minLength 1
   * @nullable
   */
  municipality?: string | null;
}
