/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * DOSPORTAL API
 * API Documentation for DOSPORTAL
 * OpenAPI spec version: 1.0.0
 */

export interface Airport {
  readonly id: string;
  name: string;
  /** @nullable */
  code_iata?: string | null;
  /** @nullable */
  code_icao?: string | null;
  /** @nullable */
  municipality?: string | null;
}
