/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * DOSPORTAL API
 * API Documentation for DOSPORTAL
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `spectral` - Processed log file into spectral file (Parquet)
 */
export type ArtifactTypeEnum = typeof ArtifactTypeEnum[keyof typeof ArtifactTypeEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ArtifactTypeEnum = {
  spectral: 'spectral',
} as const;
