/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * DOSPORTAL API
 * API Documentation for DOSPORTAL
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `PR` - Private
* `PU` - Public
* `NV` - Non-public
 */
export type DataPolicyEnum = typeof DataPolicyEnum[keyof typeof DataPolicyEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DataPolicyEnum = {
  PR: 'PR',
  PU: 'PU',
  NV: 'NV',
} as const;
