/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * DOSPORTAL API
 * API Documentation for DOSPORTAL
 * OpenAPI spec version: 1.0.0
 */

export interface DetectorManufacturerRequest {
  /**
   * @minLength 1
   * @maxLength 80
   */
  name: string;
  /**
   * @minLength 1
   * @maxLength 200
   */
  url: string;
}
