/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * DOSPORTAL API
 * API Documentation for DOSPORTAL
 * OpenAPI spec version: 1.0.0
 */

export type DetectorsQrRetrieveParams = {
/**
 * Include detector label (name and serial number) - true/false
 */
label?: string;
};
