/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * DOSPORTAL API
 * API Documentation for DOSPORTAL
 * OpenAPI spec version: 1.0.0
 */

export interface DetectorType {
  readonly id: string;
  /** @maxLength 80 */
  name: string;
  manufacturer: string;
  /**
   * @maxLength 200
   * @nullable
   */
  url?: string | null;
  /** Detector description */
  description?: string;
  readonly image: string;
}
