/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * DOSPORTAL API
 * API Documentation for DOSPORTAL
 * OpenAPI spec version: 1.0.0
 */
import type { OrganizationSummary } from './organizationSummary';
import type { DetectorType } from './detectorType';

export interface Detector {
  readonly id: string;
  readonly owner: OrganizationSummary;
  owner_id: string;
  readonly type: DetectorType;
  type_id: string;
  /** @nullable */
  image?: string | null;
  is_deleted?: boolean;
  /** @nullable */
  deleted_at?: string | null;
  /** @maxLength 80 */
  sn: string;
  /** @maxLength 150 */
  name: string;
  /**
   * Date when detector was manufactured
   * @nullable
   */
  manufactured_date?: string | null;
  /** Detector metadata, used for advanced data processing and maintaining */
  data?: unknown;
  /** @nullable */
  readonly created: string | null;
  /** @nullable */
  deleted_by?: number | null;
  /** Detector calibration */
  calib?: string[];
  access?: string[];
}
