/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * DOSPORTAL API
 * API Documentation for DOSPORTAL
 * OpenAPI spec version: 1.0.0
 */
import type { FileTypeEnum } from './fileTypeEnum';
import type { SourceTypeEnum } from './sourceTypeEnum';

export interface FileRequest {
  is_deleted?: boolean;
  /** @nullable */
  deleted_at?: string | null;
  /**
   * @minLength 1
   * @maxLength 200
   */
  filename: string;
  file: Blob;
  file_type?: FileTypeEnum;
  source_type?: SourceTypeEnum;
  metadata?: unknown;
  /** @nullable */
  deleted_by?: number | null;
  /** @nullable */
  author?: number | null;
  /** @nullable */
  owner?: string | null;
}
