/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * DOSPORTAL API
 * API Documentation for DOSPORTAL
 * OpenAPI spec version: 1.0.0
 */

export type FilesListParams = {
/**
 * Filter by file type
 */
file_type?: string;
/**
 * Filter by organization ID
 */
owner?: string;
/**
 * A page number within the paginated result set.
 */
page?: number;
};
