/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * DOSPORTAL API
 * API Documentation for DOSPORTAL
 * OpenAPI spec version: 1.0.0
 */
import type { FileTypeEnum } from './fileTypeEnum';
import type { SourceTypeEnum } from './sourceTypeEnum';

export interface File {
  readonly id: string;
  is_deleted?: boolean;
  /** @nullable */
  deleted_at?: string | null;
  /** @maxLength 200 */
  filename: string;
  file: string;
  file_type?: FileTypeEnum;
  source_type?: SourceTypeEnum;
  metadata?: unknown;
  /** @nullable */
  readonly size: number | null;
  readonly created_at: string;
  /** @nullable */
  deleted_by?: number | null;
  /** @nullable */
  author?: number | null;
  /** @nullable */
  owner?: string | null;
}
