/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * DOSPORTAL API
 * API Documentation for DOSPORTAL
 * OpenAPI spec version: 1.0.0
 */

export interface FlightRequest {
  /** @minLength 1 */
  flight_number: string;
  /** @nullable */
  departure_time?: string | null;
}
