/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * DOSPORTAL API
 * API Documentation for DOSPORTAL
 * OpenAPI spec version: 1.0.0
 */

export type LogbooksListParams = {
date_from?: string;
date_to?: string;
detector?: string;
entry_type?: string;
/**
 * A page number within the paginated result set.
 */
page?: number;
};
