/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * DOSPORTAL API
 * API Documentation for DOSPORTAL
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `D` - Debug measurement
* `S` - Static measurement
* `M` - Mobile measurement (ground)
* `C` - Civil airborne measurement
* `A` - Special airborne measurement
 */
export type MeasurementTypeEnum = typeof MeasurementTypeEnum[keyof typeof MeasurementTypeEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MeasurementTypeEnum = {
  D: 'D',
  S: 'S',
  M: 'M',
  C: 'C',
  A: 'A',
} as const;
