/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * DOSPORTAL API
 * API Documentation for DOSPORTAL
 * OpenAPI spec version: 1.0.0
 */

export type MeasurementSegmentsListParams = {
/**
 * A page number within the paginated result set.
 */
page?: number;
};
