/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * DOSPORTAL API
 * API Documentation for DOSPORTAL
 * OpenAPI spec version: 1.0.0
 */

export interface MeasurementSegmentRequest {
  measurement: string;
  spectral_record: string;
  /** @nullable */
  time_from?: string | null;
  /** @nullable */
  time_to?: string | null;
  /**
   * @minimum -2147483648
   * @maximum 2147483647
   */
  position?: number;
}
