/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * DOSPORTAL API
 * API Documentation for DOSPORTAL
 * OpenAPI spec version: 1.0.0
 */
import type { MeasurementTypeEnum } from './measurementTypeEnum';

export interface MeasurementCreateRequest {
  /**
   * @minLength 1
   * @maxLength 150
   */
  name: string;
  /** Type of measurement

* `D` - Debug measurement
* `S` - Static measurement
* `M` - Mobile measurement (ground)
* `C` - Civil airborne measurement
* `A` - Special airborne measurement */
  measurement_type?: MeasurementTypeEnum;
  description?: string;
  public?: boolean;
  /** @nullable */
  time_start?: string | null;
  /** @nullable */
  time_end?: string | null;
  /** @nullable */
  base_location_lat?: number | null;
  /** @nullable */
  base_location_lon?: number | null;
  /** @nullable */
  base_location_alt?: number | null;
  /** @nullable */
  owner_id?: string | null;
}
