/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * DOSPORTAL API
 * API Documentation for DOSPORTAL
 * OpenAPI spec version: 1.0.0
 */

export interface OrganizationUser {
  id: string;
  name: string;
  user_type: string;
  data_policy: string;
}
