/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * DOSPORTAL API
 * API Documentation for DOSPORTAL
 * OpenAPI spec version: 1.0.0
 */
import type { SpectralRecordArtifact } from './spectralRecordArtifact';

export interface PaginatedSpectralRecordArtifactList {
  count: number;
  /** @nullable */
  next?: string | null;
  /** @nullable */
  previous?: string | null;
  results: SpectralRecordArtifact[];
}
