/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * DOSPORTAL API
 * API Documentation for DOSPORTAL
 * OpenAPI spec version: 1.0.0
 */

export interface PatchedDetectorRequest {
  owner_id?: string;
  type_id?: string;
  is_deleted?: boolean;
  /** @nullable */
  deleted_at?: string | null;
  /**
   * @minLength 1
   * @maxLength 80
   */
  sn?: string;
  /**
   * @minLength 1
   * @maxLength 150
   */
  name?: string;
  /**
   * Date when detector was manufactured
   * @nullable
   */
  manufactured_date?: string | null;
  /** Detector metadata, used for advanced data processing and maintaining */
  data?: unknown;
  /** @nullable */
  deleted_by?: number | null;
  /** Detector calibration */
  calib?: string[];
  access?: string[];
}
