/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * DOSPORTAL API
 * API Documentation for DOSPORTAL
 * OpenAPI spec version: 1.0.0
 */

export interface PatchedSpectralRecordUpdateRequest {
  /**
   * Name of this record. Short and simple description of record.
   * @minLength 1
   * @maxLength 80
   * @nullable
   */
  name?: string | null;
  /** Description of the record */
  description?: string;
  /** record metadata, used for advanced data processing and maintaining */
  metadata?: unknown;
}
