/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * DOSPORTAL API
 * API Documentation for DOSPORTAL
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `pending` - Pending processing
* `processing` - Processing in progress
* `completed` - Processing completed
* `failed` - Processing failed
 */
export type ProcessingStatusEnum = typeof ProcessingStatusEnum[keyof typeof ProcessingStatusEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProcessingStatusEnum = {
  pending: 'pending',
  processing: 'processing',
  completed: 'completed',
  failed: 'failed',
} as const;
