/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * DOSPORTAL API
 * API Documentation for DOSPORTAL
 * OpenAPI spec version: 1.0.0
 */

export interface SignupRequestRequest {
  /**
   * Desired username
   * @minLength 1
   */
  username: string;
  /**
   * First name
   * @minLength 1
   */
  first_name: string;
  /**
   * Last name
   * @minLength 1
   */
  last_name: string;
  /**
   * Email address
   * @minLength 1
   */
  email: string;
  /**
   * Password (min 8 characters)
   * @minLength 1
   */
  password: string;
  /**
   * Password confirmation
   * @minLength 1
   */
  password_confirm: string;
}
