/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * DOSPORTAL API
 * API Documentation for DOSPORTAL
 * OpenAPI spec version: 1.0.0
 */

/**
 * * `uploaded` - Uploaded by user
* `generated` - Generated by system
 */
export type SourceTypeEnum = typeof SourceTypeEnum[keyof typeof SourceTypeEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SourceTypeEnum = {
  uploaded: 'uploaded',
  generated: 'generated',
} as const;
