/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * DOSPORTAL API
 * API Documentation for DOSPORTAL
 * OpenAPI spec version: 1.0.0
 */

export type SpectralRecordArtifactsListParams = {
artifact_type?: string;
/**
 * A page number within the paginated result set.
 */
page?: number;
/**
 * Filter by spectral record ID
 */
spectral_record?: string;
};
