/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * DOSPORTAL API
 * API Documentation for DOSPORTAL
 * OpenAPI spec version: 1.0.0
 */

/**
 * Serializer for creating spectral records.
 */
export interface SpectralRecordCreateRequest {
  /**
   * Name of this record. Short and simple description of record.
   * @minLength 1
   * @maxLength 80
   * @nullable
   */
  name?: string | null;
  raw_file: string;
  /** @nullable */
  detector?: string | null;
  /** Description of the record */
  description?: string;
  /**
   * Organization that owns this record
   * @nullable
   */
  owner?: string | null;
  /** record metadata, used for advanced data processing and maintaining */
  metadata?: unknown;
}
