/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * DOSPORTAL API
 * API Documentation for DOSPORTAL
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  Airport,
  AirportsListParams,
  Flight,
  FlightsListParams,
  PaginatedAirportList,
  PaginatedFlightList
} from '.././model';





/**
 * List airports.
 */
export const airportsList = (
    params?: AirportsListParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PaginatedAirportList>> => {
    
    
    return axios.default.get(
      `/api/airports/`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getAirportsListQueryKey = (params?: AirportsListParams,) => {
    return [
    `/api/airports/`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getAirportsListQueryOptions = <TData = Awaited<ReturnType<typeof airportsList>>, TError = AxiosError<unknown>>(params?: AirportsListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof airportsList>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAirportsListQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof airportsList>>> = ({ signal }) => airportsList(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof airportsList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AirportsListQueryResult = NonNullable<Awaited<ReturnType<typeof airportsList>>>
export type AirportsListQueryError = AxiosError<unknown>


export function useAirportsList<TData = Awaited<ReturnType<typeof airportsList>>, TError = AxiosError<unknown>>(
 params: undefined |  AirportsListParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof airportsList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof airportsList>>,
          TError,
          Awaited<ReturnType<typeof airportsList>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAirportsList<TData = Awaited<ReturnType<typeof airportsList>>, TError = AxiosError<unknown>>(
 params?: AirportsListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof airportsList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof airportsList>>,
          TError,
          Awaited<ReturnType<typeof airportsList>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAirportsList<TData = Awaited<ReturnType<typeof airportsList>>, TError = AxiosError<unknown>>(
 params?: AirportsListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof airportsList>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useAirportsList<TData = Awaited<ReturnType<typeof airportsList>>, TError = AxiosError<unknown>>(
 params?: AirportsListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof airportsList>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAirportsListQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Get airport detail.
 */
export const airportsRetrieve = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Airport>> => {
    
    
    return axios.default.get(
      `/api/airports/${id}/`,options
    );
  }




export const getAirportsRetrieveQueryKey = (id?: string,) => {
    return [
    `/api/airports/${id}/`
    ] as const;
    }

    
export const getAirportsRetrieveQueryOptions = <TData = Awaited<ReturnType<typeof airportsRetrieve>>, TError = AxiosError<unknown>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof airportsRetrieve>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAirportsRetrieveQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof airportsRetrieve>>> = ({ signal }) => airportsRetrieve(id, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof airportsRetrieve>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AirportsRetrieveQueryResult = NonNullable<Awaited<ReturnType<typeof airportsRetrieve>>>
export type AirportsRetrieveQueryError = AxiosError<unknown>


export function useAirportsRetrieve<TData = Awaited<ReturnType<typeof airportsRetrieve>>, TError = AxiosError<unknown>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof airportsRetrieve>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof airportsRetrieve>>,
          TError,
          Awaited<ReturnType<typeof airportsRetrieve>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAirportsRetrieve<TData = Awaited<ReturnType<typeof airportsRetrieve>>, TError = AxiosError<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof airportsRetrieve>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof airportsRetrieve>>,
          TError,
          Awaited<ReturnType<typeof airportsRetrieve>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAirportsRetrieve<TData = Awaited<ReturnType<typeof airportsRetrieve>>, TError = AxiosError<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof airportsRetrieve>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useAirportsRetrieve<TData = Awaited<ReturnType<typeof airportsRetrieve>>, TError = AxiosError<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof airportsRetrieve>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAirportsRetrieveQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * List flights.
 */
export const flightsList = (
    params?: FlightsListParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PaginatedFlightList>> => {
    
    
    return axios.default.get(
      `/api/flights/`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getFlightsListQueryKey = (params?: FlightsListParams,) => {
    return [
    `/api/flights/`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getFlightsListQueryOptions = <TData = Awaited<ReturnType<typeof flightsList>>, TError = AxiosError<unknown>>(params?: FlightsListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof flightsList>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFlightsListQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof flightsList>>> = ({ signal }) => flightsList(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof flightsList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FlightsListQueryResult = NonNullable<Awaited<ReturnType<typeof flightsList>>>
export type FlightsListQueryError = AxiosError<unknown>


export function useFlightsList<TData = Awaited<ReturnType<typeof flightsList>>, TError = AxiosError<unknown>>(
 params: undefined |  FlightsListParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof flightsList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof flightsList>>,
          TError,
          Awaited<ReturnType<typeof flightsList>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFlightsList<TData = Awaited<ReturnType<typeof flightsList>>, TError = AxiosError<unknown>>(
 params?: FlightsListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof flightsList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof flightsList>>,
          TError,
          Awaited<ReturnType<typeof flightsList>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFlightsList<TData = Awaited<ReturnType<typeof flightsList>>, TError = AxiosError<unknown>>(
 params?: FlightsListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof flightsList>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useFlightsList<TData = Awaited<ReturnType<typeof flightsList>>, TError = AxiosError<unknown>>(
 params?: FlightsListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof flightsList>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFlightsListQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Get flight detail.
 */
export const flightsRetrieve = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Flight>> => {
    
    
    return axios.default.get(
      `/api/flights/${id}/`,options
    );
  }




export const getFlightsRetrieveQueryKey = (id?: string,) => {
    return [
    `/api/flights/${id}/`
    ] as const;
    }

    
export const getFlightsRetrieveQueryOptions = <TData = Awaited<ReturnType<typeof flightsRetrieve>>, TError = AxiosError<unknown>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof flightsRetrieve>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFlightsRetrieveQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof flightsRetrieve>>> = ({ signal }) => flightsRetrieve(id, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof flightsRetrieve>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type FlightsRetrieveQueryResult = NonNullable<Awaited<ReturnType<typeof flightsRetrieve>>>
export type FlightsRetrieveQueryError = AxiosError<unknown>


export function useFlightsRetrieve<TData = Awaited<ReturnType<typeof flightsRetrieve>>, TError = AxiosError<unknown>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof flightsRetrieve>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof flightsRetrieve>>,
          TError,
          Awaited<ReturnType<typeof flightsRetrieve>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFlightsRetrieve<TData = Awaited<ReturnType<typeof flightsRetrieve>>, TError = AxiosError<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof flightsRetrieve>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof flightsRetrieve>>,
          TError,
          Awaited<ReturnType<typeof flightsRetrieve>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useFlightsRetrieve<TData = Awaited<ReturnType<typeof flightsRetrieve>>, TError = AxiosError<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof flightsRetrieve>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useFlightsRetrieve<TData = Awaited<ReturnType<typeof flightsRetrieve>>, TError = AxiosError<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof flightsRetrieve>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getFlightsRetrieveQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




