/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * DOSPORTAL API
 * API Documentation for DOSPORTAL
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  Detector,
  DetectorLogbook,
  DetectorLogbookRequest,
  DetectorManufacturer,
  DetectorManufacturerRequest,
  DetectorManufacturersListParams,
  DetectorRequest,
  DetectorType,
  DetectorTypeRequest,
  DetectorTypesListParams,
  DetectorsListParams,
  DetectorsQrRetrieveParams,
  LogbooksListParams,
  PaginatedDetectorList,
  PaginatedDetectorLogbookList,
  PaginatedDetectorManufacturerList,
  PaginatedDetectorTypeList,
  PatchedDetectorLogbookRequest,
  PatchedDetectorManufacturerRequest,
  PatchedDetectorRequest,
  PatchedDetectorTypeRequest
} from '.././model';





/**
 * List all detector manufacturers.
 */
export const detectorManufacturersList = (
    params?: DetectorManufacturersListParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PaginatedDetectorManufacturerList>> => {
    
    
    return axios.default.get(
      `/api/detector-manufacturers/`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getDetectorManufacturersListQueryKey = (params?: DetectorManufacturersListParams,) => {
    return [
    `/api/detector-manufacturers/`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getDetectorManufacturersListQueryOptions = <TData = Awaited<ReturnType<typeof detectorManufacturersList>>, TError = AxiosError<unknown>>(params?: DetectorManufacturersListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof detectorManufacturersList>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDetectorManufacturersListQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof detectorManufacturersList>>> = ({ signal }) => detectorManufacturersList(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof detectorManufacturersList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DetectorManufacturersListQueryResult = NonNullable<Awaited<ReturnType<typeof detectorManufacturersList>>>
export type DetectorManufacturersListQueryError = AxiosError<unknown>


export function useDetectorManufacturersList<TData = Awaited<ReturnType<typeof detectorManufacturersList>>, TError = AxiosError<unknown>>(
 params: undefined |  DetectorManufacturersListParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof detectorManufacturersList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof detectorManufacturersList>>,
          TError,
          Awaited<ReturnType<typeof detectorManufacturersList>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDetectorManufacturersList<TData = Awaited<ReturnType<typeof detectorManufacturersList>>, TError = AxiosError<unknown>>(
 params?: DetectorManufacturersListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof detectorManufacturersList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof detectorManufacturersList>>,
          TError,
          Awaited<ReturnType<typeof detectorManufacturersList>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDetectorManufacturersList<TData = Awaited<ReturnType<typeof detectorManufacturersList>>, TError = AxiosError<unknown>>(
 params?: DetectorManufacturersListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof detectorManufacturersList>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useDetectorManufacturersList<TData = Awaited<ReturnType<typeof detectorManufacturersList>>, TError = AxiosError<unknown>>(
 params?: DetectorManufacturersListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof detectorManufacturersList>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDetectorManufacturersListQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Create a detector manufacturer.
 */
export const detectorManufacturersCreate = (
    detectorManufacturerRequest: DetectorManufacturerRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<DetectorManufacturer>> => {
    
    
    return axios.default.post(
      `/api/detector-manufacturers/`,
      detectorManufacturerRequest,options
    );
  }



export const getDetectorManufacturersCreateMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof detectorManufacturersCreate>>, TError,{data: DetectorManufacturerRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof detectorManufacturersCreate>>, TError,{data: DetectorManufacturerRequest}, TContext> => {

const mutationKey = ['detectorManufacturersCreate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof detectorManufacturersCreate>>, {data: DetectorManufacturerRequest}> = (props) => {
          const {data} = props ?? {};

          return  detectorManufacturersCreate(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DetectorManufacturersCreateMutationResult = NonNullable<Awaited<ReturnType<typeof detectorManufacturersCreate>>>
    export type DetectorManufacturersCreateMutationBody = DetectorManufacturerRequest
    export type DetectorManufacturersCreateMutationError = AxiosError<unknown>

    export const useDetectorManufacturersCreate = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof detectorManufacturersCreate>>, TError,{data: DetectorManufacturerRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof detectorManufacturersCreate>>,
        TError,
        {data: DetectorManufacturerRequest},
        TContext
      > => {

      const mutationOptions = getDetectorManufacturersCreateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Get detector manufacturer by ID.
 */
export const detectorManufacturersRetrieve = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<DetectorManufacturer>> => {
    
    
    return axios.default.get(
      `/api/detector-manufacturers/${id}/`,options
    );
  }




export const getDetectorManufacturersRetrieveQueryKey = (id?: string,) => {
    return [
    `/api/detector-manufacturers/${id}/`
    ] as const;
    }

    
export const getDetectorManufacturersRetrieveQueryOptions = <TData = Awaited<ReturnType<typeof detectorManufacturersRetrieve>>, TError = AxiosError<unknown>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof detectorManufacturersRetrieve>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDetectorManufacturersRetrieveQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof detectorManufacturersRetrieve>>> = ({ signal }) => detectorManufacturersRetrieve(id, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof detectorManufacturersRetrieve>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DetectorManufacturersRetrieveQueryResult = NonNullable<Awaited<ReturnType<typeof detectorManufacturersRetrieve>>>
export type DetectorManufacturersRetrieveQueryError = AxiosError<unknown>


export function useDetectorManufacturersRetrieve<TData = Awaited<ReturnType<typeof detectorManufacturersRetrieve>>, TError = AxiosError<unknown>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof detectorManufacturersRetrieve>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof detectorManufacturersRetrieve>>,
          TError,
          Awaited<ReturnType<typeof detectorManufacturersRetrieve>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDetectorManufacturersRetrieve<TData = Awaited<ReturnType<typeof detectorManufacturersRetrieve>>, TError = AxiosError<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof detectorManufacturersRetrieve>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof detectorManufacturersRetrieve>>,
          TError,
          Awaited<ReturnType<typeof detectorManufacturersRetrieve>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDetectorManufacturersRetrieve<TData = Awaited<ReturnType<typeof detectorManufacturersRetrieve>>, TError = AxiosError<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof detectorManufacturersRetrieve>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useDetectorManufacturersRetrieve<TData = Awaited<ReturnType<typeof detectorManufacturersRetrieve>>, TError = AxiosError<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof detectorManufacturersRetrieve>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDetectorManufacturersRetrieveQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Update a detector manufacturer.
 */
export const detectorManufacturersUpdate = (
    id: string,
    detectorManufacturerRequest: DetectorManufacturerRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<DetectorManufacturer>> => {
    
    
    return axios.default.put(
      `/api/detector-manufacturers/${id}/`,
      detectorManufacturerRequest,options
    );
  }



export const getDetectorManufacturersUpdateMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof detectorManufacturersUpdate>>, TError,{id: string;data: DetectorManufacturerRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof detectorManufacturersUpdate>>, TError,{id: string;data: DetectorManufacturerRequest}, TContext> => {

const mutationKey = ['detectorManufacturersUpdate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof detectorManufacturersUpdate>>, {id: string;data: DetectorManufacturerRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  detectorManufacturersUpdate(id,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DetectorManufacturersUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof detectorManufacturersUpdate>>>
    export type DetectorManufacturersUpdateMutationBody = DetectorManufacturerRequest
    export type DetectorManufacturersUpdateMutationError = AxiosError<unknown>

    export const useDetectorManufacturersUpdate = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof detectorManufacturersUpdate>>, TError,{id: string;data: DetectorManufacturerRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof detectorManufacturersUpdate>>,
        TError,
        {id: string;data: DetectorManufacturerRequest},
        TContext
      > => {

      const mutationOptions = getDetectorManufacturersUpdateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Partially update a detector manufacturer.
 */
export const detectorManufacturersPartialUpdate = (
    id: string,
    patchedDetectorManufacturerRequest: PatchedDetectorManufacturerRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<DetectorManufacturer>> => {
    
    
    return axios.default.patch(
      `/api/detector-manufacturers/${id}/`,
      patchedDetectorManufacturerRequest,options
    );
  }



export const getDetectorManufacturersPartialUpdateMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof detectorManufacturersPartialUpdate>>, TError,{id: string;data: PatchedDetectorManufacturerRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof detectorManufacturersPartialUpdate>>, TError,{id: string;data: PatchedDetectorManufacturerRequest}, TContext> => {

const mutationKey = ['detectorManufacturersPartialUpdate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof detectorManufacturersPartialUpdate>>, {id: string;data: PatchedDetectorManufacturerRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  detectorManufacturersPartialUpdate(id,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DetectorManufacturersPartialUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof detectorManufacturersPartialUpdate>>>
    export type DetectorManufacturersPartialUpdateMutationBody = PatchedDetectorManufacturerRequest
    export type DetectorManufacturersPartialUpdateMutationError = AxiosError<unknown>

    export const useDetectorManufacturersPartialUpdate = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof detectorManufacturersPartialUpdate>>, TError,{id: string;data: PatchedDetectorManufacturerRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof detectorManufacturersPartialUpdate>>,
        TError,
        {id: string;data: PatchedDetectorManufacturerRequest},
        TContext
      > => {

      const mutationOptions = getDetectorManufacturersPartialUpdateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Delete a detector manufacturer.
 */
export const detectorManufacturersDestroy = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.delete(
      `/api/detector-manufacturers/${id}/`,options
    );
  }



export const getDetectorManufacturersDestroyMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof detectorManufacturersDestroy>>, TError,{id: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof detectorManufacturersDestroy>>, TError,{id: string}, TContext> => {

const mutationKey = ['detectorManufacturersDestroy'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof detectorManufacturersDestroy>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  detectorManufacturersDestroy(id,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DetectorManufacturersDestroyMutationResult = NonNullable<Awaited<ReturnType<typeof detectorManufacturersDestroy>>>
    
    export type DetectorManufacturersDestroyMutationError = AxiosError<unknown>

    export const useDetectorManufacturersDestroy = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof detectorManufacturersDestroy>>, TError,{id: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof detectorManufacturersDestroy>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDetectorManufacturersDestroyMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * List all detector types.
 */
export const detectorTypesList = (
    params?: DetectorTypesListParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PaginatedDetectorTypeList>> => {
    
    
    return axios.default.get(
      `/api/detector-types/`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getDetectorTypesListQueryKey = (params?: DetectorTypesListParams,) => {
    return [
    `/api/detector-types/`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getDetectorTypesListQueryOptions = <TData = Awaited<ReturnType<typeof detectorTypesList>>, TError = AxiosError<unknown>>(params?: DetectorTypesListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof detectorTypesList>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDetectorTypesListQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof detectorTypesList>>> = ({ signal }) => detectorTypesList(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof detectorTypesList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DetectorTypesListQueryResult = NonNullable<Awaited<ReturnType<typeof detectorTypesList>>>
export type DetectorTypesListQueryError = AxiosError<unknown>


export function useDetectorTypesList<TData = Awaited<ReturnType<typeof detectorTypesList>>, TError = AxiosError<unknown>>(
 params: undefined |  DetectorTypesListParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof detectorTypesList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof detectorTypesList>>,
          TError,
          Awaited<ReturnType<typeof detectorTypesList>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDetectorTypesList<TData = Awaited<ReturnType<typeof detectorTypesList>>, TError = AxiosError<unknown>>(
 params?: DetectorTypesListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof detectorTypesList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof detectorTypesList>>,
          TError,
          Awaited<ReturnType<typeof detectorTypesList>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDetectorTypesList<TData = Awaited<ReturnType<typeof detectorTypesList>>, TError = AxiosError<unknown>>(
 params?: DetectorTypesListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof detectorTypesList>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useDetectorTypesList<TData = Awaited<ReturnType<typeof detectorTypesList>>, TError = AxiosError<unknown>>(
 params?: DetectorTypesListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof detectorTypesList>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDetectorTypesListQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Create a detector type.
 */
export const detectorTypesCreate = (
    detectorTypeRequest: DetectorTypeRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<DetectorType>> => {
    
    
    return axios.default.post(
      `/api/detector-types/`,
      detectorTypeRequest,options
    );
  }



export const getDetectorTypesCreateMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof detectorTypesCreate>>, TError,{data: DetectorTypeRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof detectorTypesCreate>>, TError,{data: DetectorTypeRequest}, TContext> => {

const mutationKey = ['detectorTypesCreate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof detectorTypesCreate>>, {data: DetectorTypeRequest}> = (props) => {
          const {data} = props ?? {};

          return  detectorTypesCreate(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DetectorTypesCreateMutationResult = NonNullable<Awaited<ReturnType<typeof detectorTypesCreate>>>
    export type DetectorTypesCreateMutationBody = DetectorTypeRequest
    export type DetectorTypesCreateMutationError = AxiosError<unknown>

    export const useDetectorTypesCreate = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof detectorTypesCreate>>, TError,{data: DetectorTypeRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof detectorTypesCreate>>,
        TError,
        {data: DetectorTypeRequest},
        TContext
      > => {

      const mutationOptions = getDetectorTypesCreateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Get detector type by ID.
 */
export const detectorTypesRetrieve = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<DetectorType>> => {
    
    
    return axios.default.get(
      `/api/detector-types/${id}/`,options
    );
  }




export const getDetectorTypesRetrieveQueryKey = (id?: string,) => {
    return [
    `/api/detector-types/${id}/`
    ] as const;
    }

    
export const getDetectorTypesRetrieveQueryOptions = <TData = Awaited<ReturnType<typeof detectorTypesRetrieve>>, TError = AxiosError<unknown>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof detectorTypesRetrieve>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDetectorTypesRetrieveQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof detectorTypesRetrieve>>> = ({ signal }) => detectorTypesRetrieve(id, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof detectorTypesRetrieve>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DetectorTypesRetrieveQueryResult = NonNullable<Awaited<ReturnType<typeof detectorTypesRetrieve>>>
export type DetectorTypesRetrieveQueryError = AxiosError<unknown>


export function useDetectorTypesRetrieve<TData = Awaited<ReturnType<typeof detectorTypesRetrieve>>, TError = AxiosError<unknown>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof detectorTypesRetrieve>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof detectorTypesRetrieve>>,
          TError,
          Awaited<ReturnType<typeof detectorTypesRetrieve>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDetectorTypesRetrieve<TData = Awaited<ReturnType<typeof detectorTypesRetrieve>>, TError = AxiosError<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof detectorTypesRetrieve>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof detectorTypesRetrieve>>,
          TError,
          Awaited<ReturnType<typeof detectorTypesRetrieve>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDetectorTypesRetrieve<TData = Awaited<ReturnType<typeof detectorTypesRetrieve>>, TError = AxiosError<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof detectorTypesRetrieve>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useDetectorTypesRetrieve<TData = Awaited<ReturnType<typeof detectorTypesRetrieve>>, TError = AxiosError<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof detectorTypesRetrieve>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDetectorTypesRetrieveQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Update a detector type.
 */
export const detectorTypesUpdate = (
    id: string,
    detectorTypeRequest: DetectorTypeRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<DetectorType>> => {
    
    
    return axios.default.put(
      `/api/detector-types/${id}/`,
      detectorTypeRequest,options
    );
  }



export const getDetectorTypesUpdateMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof detectorTypesUpdate>>, TError,{id: string;data: DetectorTypeRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof detectorTypesUpdate>>, TError,{id: string;data: DetectorTypeRequest}, TContext> => {

const mutationKey = ['detectorTypesUpdate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof detectorTypesUpdate>>, {id: string;data: DetectorTypeRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  detectorTypesUpdate(id,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DetectorTypesUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof detectorTypesUpdate>>>
    export type DetectorTypesUpdateMutationBody = DetectorTypeRequest
    export type DetectorTypesUpdateMutationError = AxiosError<unknown>

    export const useDetectorTypesUpdate = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof detectorTypesUpdate>>, TError,{id: string;data: DetectorTypeRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof detectorTypesUpdate>>,
        TError,
        {id: string;data: DetectorTypeRequest},
        TContext
      > => {

      const mutationOptions = getDetectorTypesUpdateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Partially update a detector type.
 */
export const detectorTypesPartialUpdate = (
    id: string,
    patchedDetectorTypeRequest: PatchedDetectorTypeRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<DetectorType>> => {
    
    
    return axios.default.patch(
      `/api/detector-types/${id}/`,
      patchedDetectorTypeRequest,options
    );
  }



export const getDetectorTypesPartialUpdateMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof detectorTypesPartialUpdate>>, TError,{id: string;data: PatchedDetectorTypeRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof detectorTypesPartialUpdate>>, TError,{id: string;data: PatchedDetectorTypeRequest}, TContext> => {

const mutationKey = ['detectorTypesPartialUpdate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof detectorTypesPartialUpdate>>, {id: string;data: PatchedDetectorTypeRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  detectorTypesPartialUpdate(id,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DetectorTypesPartialUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof detectorTypesPartialUpdate>>>
    export type DetectorTypesPartialUpdateMutationBody = PatchedDetectorTypeRequest
    export type DetectorTypesPartialUpdateMutationError = AxiosError<unknown>

    export const useDetectorTypesPartialUpdate = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof detectorTypesPartialUpdate>>, TError,{id: string;data: PatchedDetectorTypeRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof detectorTypesPartialUpdate>>,
        TError,
        {id: string;data: PatchedDetectorTypeRequest},
        TContext
      > => {

      const mutationOptions = getDetectorTypesPartialUpdateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Delete a detector type.
 */
export const detectorTypesDestroy = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.delete(
      `/api/detector-types/${id}/`,options
    );
  }



export const getDetectorTypesDestroyMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof detectorTypesDestroy>>, TError,{id: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof detectorTypesDestroy>>, TError,{id: string}, TContext> => {

const mutationKey = ['detectorTypesDestroy'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof detectorTypesDestroy>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  detectorTypesDestroy(id,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DetectorTypesDestroyMutationResult = NonNullable<Awaited<ReturnType<typeof detectorTypesDestroy>>>
    
    export type DetectorTypesDestroyMutationError = AxiosError<unknown>

    export const useDetectorTypesDestroy = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof detectorTypesDestroy>>, TError,{id: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof detectorTypesDestroy>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDetectorTypesDestroyMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * List detectors accessible to the current user (filtered by org membership).
 */
export const detectorsList = (
    params?: DetectorsListParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PaginatedDetectorList>> => {
    
    
    return axios.default.get(
      `/api/detectors/`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getDetectorsListQueryKey = (params?: DetectorsListParams,) => {
    return [
    `/api/detectors/`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getDetectorsListQueryOptions = <TData = Awaited<ReturnType<typeof detectorsList>>, TError = AxiosError<unknown>>(params?: DetectorsListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof detectorsList>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDetectorsListQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof detectorsList>>> = ({ signal }) => detectorsList(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof detectorsList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DetectorsListQueryResult = NonNullable<Awaited<ReturnType<typeof detectorsList>>>
export type DetectorsListQueryError = AxiosError<unknown>


export function useDetectorsList<TData = Awaited<ReturnType<typeof detectorsList>>, TError = AxiosError<unknown>>(
 params: undefined |  DetectorsListParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof detectorsList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof detectorsList>>,
          TError,
          Awaited<ReturnType<typeof detectorsList>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDetectorsList<TData = Awaited<ReturnType<typeof detectorsList>>, TError = AxiosError<unknown>>(
 params?: DetectorsListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof detectorsList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof detectorsList>>,
          TError,
          Awaited<ReturnType<typeof detectorsList>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDetectorsList<TData = Awaited<ReturnType<typeof detectorsList>>, TError = AxiosError<unknown>>(
 params?: DetectorsListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof detectorsList>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useDetectorsList<TData = Awaited<ReturnType<typeof detectorsList>>, TError = AxiosError<unknown>>(
 params?: DetectorsListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof detectorsList>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDetectorsListQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Create a detector. The owner org must be one where the user is admin/owner.
 */
export const detectorsCreate = (
    detectorRequest: DetectorRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Detector>> => {
    
    
    return axios.default.post(
      `/api/detectors/`,
      detectorRequest,options
    );
  }



export const getDetectorsCreateMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof detectorsCreate>>, TError,{data: DetectorRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof detectorsCreate>>, TError,{data: DetectorRequest}, TContext> => {

const mutationKey = ['detectorsCreate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof detectorsCreate>>, {data: DetectorRequest}> = (props) => {
          const {data} = props ?? {};

          return  detectorsCreate(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DetectorsCreateMutationResult = NonNullable<Awaited<ReturnType<typeof detectorsCreate>>>
    export type DetectorsCreateMutationBody = DetectorRequest
    export type DetectorsCreateMutationError = AxiosError<unknown>

    export const useDetectorsCreate = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof detectorsCreate>>, TError,{data: DetectorRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof detectorsCreate>>,
        TError,
        {data: DetectorRequest},
        TContext
      > => {

      const mutationOptions = getDetectorsCreateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Generate QR code for a specific detector
 */
export const detectorsQrRetrieve = (
    detectorId: string,
    params?: DetectorsQrRetrieveParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.get(
      `/api/detectors/${detectorId}/qr/`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getDetectorsQrRetrieveQueryKey = (detectorId?: string,
    params?: DetectorsQrRetrieveParams,) => {
    return [
    `/api/detectors/${detectorId}/qr/`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getDetectorsQrRetrieveQueryOptions = <TData = Awaited<ReturnType<typeof detectorsQrRetrieve>>, TError = AxiosError<unknown>>(detectorId: string,
    params?: DetectorsQrRetrieveParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof detectorsQrRetrieve>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDetectorsQrRetrieveQueryKey(detectorId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof detectorsQrRetrieve>>> = ({ signal }) => detectorsQrRetrieve(detectorId,params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(detectorId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof detectorsQrRetrieve>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DetectorsQrRetrieveQueryResult = NonNullable<Awaited<ReturnType<typeof detectorsQrRetrieve>>>
export type DetectorsQrRetrieveQueryError = AxiosError<unknown>


export function useDetectorsQrRetrieve<TData = Awaited<ReturnType<typeof detectorsQrRetrieve>>, TError = AxiosError<unknown>>(
 detectorId: string,
    params: undefined |  DetectorsQrRetrieveParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof detectorsQrRetrieve>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof detectorsQrRetrieve>>,
          TError,
          Awaited<ReturnType<typeof detectorsQrRetrieve>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDetectorsQrRetrieve<TData = Awaited<ReturnType<typeof detectorsQrRetrieve>>, TError = AxiosError<unknown>>(
 detectorId: string,
    params?: DetectorsQrRetrieveParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof detectorsQrRetrieve>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof detectorsQrRetrieve>>,
          TError,
          Awaited<ReturnType<typeof detectorsQrRetrieve>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDetectorsQrRetrieve<TData = Awaited<ReturnType<typeof detectorsQrRetrieve>>, TError = AxiosError<unknown>>(
 detectorId: string,
    params?: DetectorsQrRetrieveParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof detectorsQrRetrieve>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useDetectorsQrRetrieve<TData = Awaited<ReturnType<typeof detectorsQrRetrieve>>, TError = AxiosError<unknown>>(
 detectorId: string,
    params?: DetectorsQrRetrieveParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof detectorsQrRetrieve>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDetectorsQrRetrieveQueryOptions(detectorId,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Get detector detail by ID.
 */
export const detectorsRetrieve = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Detector>> => {
    
    
    return axios.default.get(
      `/api/detectors/${id}/`,options
    );
  }




export const getDetectorsRetrieveQueryKey = (id?: string,) => {
    return [
    `/api/detectors/${id}/`
    ] as const;
    }

    
export const getDetectorsRetrieveQueryOptions = <TData = Awaited<ReturnType<typeof detectorsRetrieve>>, TError = AxiosError<unknown>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof detectorsRetrieve>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDetectorsRetrieveQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof detectorsRetrieve>>> = ({ signal }) => detectorsRetrieve(id, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof detectorsRetrieve>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DetectorsRetrieveQueryResult = NonNullable<Awaited<ReturnType<typeof detectorsRetrieve>>>
export type DetectorsRetrieveQueryError = AxiosError<unknown>


export function useDetectorsRetrieve<TData = Awaited<ReturnType<typeof detectorsRetrieve>>, TError = AxiosError<unknown>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof detectorsRetrieve>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof detectorsRetrieve>>,
          TError,
          Awaited<ReturnType<typeof detectorsRetrieve>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDetectorsRetrieve<TData = Awaited<ReturnType<typeof detectorsRetrieve>>, TError = AxiosError<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof detectorsRetrieve>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof detectorsRetrieve>>,
          TError,
          Awaited<ReturnType<typeof detectorsRetrieve>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDetectorsRetrieve<TData = Awaited<ReturnType<typeof detectorsRetrieve>>, TError = AxiosError<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof detectorsRetrieve>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useDetectorsRetrieve<TData = Awaited<ReturnType<typeof detectorsRetrieve>>, TError = AxiosError<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof detectorsRetrieve>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDetectorsRetrieveQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Update a detector (org admin/owner only).
 */
export const detectorsUpdate = (
    id: string,
    detectorRequest: DetectorRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Detector>> => {
    
    
    return axios.default.put(
      `/api/detectors/${id}/`,
      detectorRequest,options
    );
  }



export const getDetectorsUpdateMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof detectorsUpdate>>, TError,{id: string;data: DetectorRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof detectorsUpdate>>, TError,{id: string;data: DetectorRequest}, TContext> => {

const mutationKey = ['detectorsUpdate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof detectorsUpdate>>, {id: string;data: DetectorRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  detectorsUpdate(id,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DetectorsUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof detectorsUpdate>>>
    export type DetectorsUpdateMutationBody = DetectorRequest
    export type DetectorsUpdateMutationError = AxiosError<unknown>

    export const useDetectorsUpdate = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof detectorsUpdate>>, TError,{id: string;data: DetectorRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof detectorsUpdate>>,
        TError,
        {id: string;data: DetectorRequest},
        TContext
      > => {

      const mutationOptions = getDetectorsUpdateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Partially update a detector (org admin/owner only).
 */
export const detectorsPartialUpdate = (
    id: string,
    patchedDetectorRequest: PatchedDetectorRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Detector>> => {
    
    
    return axios.default.patch(
      `/api/detectors/${id}/`,
      patchedDetectorRequest,options
    );
  }



export const getDetectorsPartialUpdateMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof detectorsPartialUpdate>>, TError,{id: string;data: PatchedDetectorRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof detectorsPartialUpdate>>, TError,{id: string;data: PatchedDetectorRequest}, TContext> => {

const mutationKey = ['detectorsPartialUpdate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof detectorsPartialUpdate>>, {id: string;data: PatchedDetectorRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  detectorsPartialUpdate(id,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DetectorsPartialUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof detectorsPartialUpdate>>>
    export type DetectorsPartialUpdateMutationBody = PatchedDetectorRequest
    export type DetectorsPartialUpdateMutationError = AxiosError<unknown>

    export const useDetectorsPartialUpdate = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof detectorsPartialUpdate>>, TError,{id: string;data: PatchedDetectorRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof detectorsPartialUpdate>>,
        TError,
        {id: string;data: PatchedDetectorRequest},
        TContext
      > => {

      const mutationOptions = getDetectorsPartialUpdateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Soft-delete a detector (org admin/owner only).
 */
export const detectorsDestroy = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.delete(
      `/api/detectors/${id}/`,options
    );
  }



export const getDetectorsDestroyMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof detectorsDestroy>>, TError,{id: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof detectorsDestroy>>, TError,{id: string}, TContext> => {

const mutationKey = ['detectorsDestroy'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof detectorsDestroy>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  detectorsDestroy(id,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DetectorsDestroyMutationResult = NonNullable<Awaited<ReturnType<typeof detectorsDestroy>>>
    
    export type DetectorsDestroyMutationError = AxiosError<unknown>

    export const useDetectorsDestroy = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof detectorsDestroy>>, TError,{id: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof detectorsDestroy>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDetectorsDestroyMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * List detector logbook entries with optional filters.
 */
export const logbooksList = (
    params?: LogbooksListParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PaginatedDetectorLogbookList>> => {
    
    
    return axios.default.get(
      `/api/logbooks/`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getLogbooksListQueryKey = (params?: LogbooksListParams,) => {
    return [
    `/api/logbooks/`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getLogbooksListQueryOptions = <TData = Awaited<ReturnType<typeof logbooksList>>, TError = AxiosError<unknown>>(params?: LogbooksListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof logbooksList>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getLogbooksListQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof logbooksList>>> = ({ signal }) => logbooksList(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof logbooksList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type LogbooksListQueryResult = NonNullable<Awaited<ReturnType<typeof logbooksList>>>
export type LogbooksListQueryError = AxiosError<unknown>


export function useLogbooksList<TData = Awaited<ReturnType<typeof logbooksList>>, TError = AxiosError<unknown>>(
 params: undefined |  LogbooksListParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof logbooksList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof logbooksList>>,
          TError,
          Awaited<ReturnType<typeof logbooksList>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useLogbooksList<TData = Awaited<ReturnType<typeof logbooksList>>, TError = AxiosError<unknown>>(
 params?: LogbooksListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof logbooksList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof logbooksList>>,
          TError,
          Awaited<ReturnType<typeof logbooksList>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useLogbooksList<TData = Awaited<ReturnType<typeof logbooksList>>, TError = AxiosError<unknown>>(
 params?: LogbooksListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof logbooksList>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useLogbooksList<TData = Awaited<ReturnType<typeof logbooksList>>, TError = AxiosError<unknown>>(
 params?: LogbooksListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof logbooksList>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getLogbooksListQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Create a logbook entry.
 */
export const logbooksCreate = (
    detectorLogbookRequest: DetectorLogbookRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<DetectorLogbook>> => {
    
    
    return axios.default.post(
      `/api/logbooks/`,
      detectorLogbookRequest,options
    );
  }



export const getLogbooksCreateMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof logbooksCreate>>, TError,{data: DetectorLogbookRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof logbooksCreate>>, TError,{data: DetectorLogbookRequest}, TContext> => {

const mutationKey = ['logbooksCreate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof logbooksCreate>>, {data: DetectorLogbookRequest}> = (props) => {
          const {data} = props ?? {};

          return  logbooksCreate(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type LogbooksCreateMutationResult = NonNullable<Awaited<ReturnType<typeof logbooksCreate>>>
    export type LogbooksCreateMutationBody = DetectorLogbookRequest
    export type LogbooksCreateMutationError = AxiosError<unknown>

    export const useLogbooksCreate = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof logbooksCreate>>, TError,{data: DetectorLogbookRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof logbooksCreate>>,
        TError,
        {data: DetectorLogbookRequest},
        TContext
      > => {

      const mutationOptions = getLogbooksCreateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Get a logbook entry by ID.
 */
export const logbooksRetrieve = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<DetectorLogbook>> => {
    
    
    return axios.default.get(
      `/api/logbooks/${id}/`,options
    );
  }




export const getLogbooksRetrieveQueryKey = (id?: string,) => {
    return [
    `/api/logbooks/${id}/`
    ] as const;
    }

    
export const getLogbooksRetrieveQueryOptions = <TData = Awaited<ReturnType<typeof logbooksRetrieve>>, TError = AxiosError<unknown>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof logbooksRetrieve>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getLogbooksRetrieveQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof logbooksRetrieve>>> = ({ signal }) => logbooksRetrieve(id, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof logbooksRetrieve>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type LogbooksRetrieveQueryResult = NonNullable<Awaited<ReturnType<typeof logbooksRetrieve>>>
export type LogbooksRetrieveQueryError = AxiosError<unknown>


export function useLogbooksRetrieve<TData = Awaited<ReturnType<typeof logbooksRetrieve>>, TError = AxiosError<unknown>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof logbooksRetrieve>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof logbooksRetrieve>>,
          TError,
          Awaited<ReturnType<typeof logbooksRetrieve>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useLogbooksRetrieve<TData = Awaited<ReturnType<typeof logbooksRetrieve>>, TError = AxiosError<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof logbooksRetrieve>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof logbooksRetrieve>>,
          TError,
          Awaited<ReturnType<typeof logbooksRetrieve>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useLogbooksRetrieve<TData = Awaited<ReturnType<typeof logbooksRetrieve>>, TError = AxiosError<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof logbooksRetrieve>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useLogbooksRetrieve<TData = Awaited<ReturnType<typeof logbooksRetrieve>>, TError = AxiosError<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof logbooksRetrieve>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getLogbooksRetrieveQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Update a logbook entry.
 */
export const logbooksUpdate = (
    id: string,
    detectorLogbookRequest: DetectorLogbookRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<DetectorLogbook>> => {
    
    
    return axios.default.put(
      `/api/logbooks/${id}/`,
      detectorLogbookRequest,options
    );
  }



export const getLogbooksUpdateMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof logbooksUpdate>>, TError,{id: string;data: DetectorLogbookRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof logbooksUpdate>>, TError,{id: string;data: DetectorLogbookRequest}, TContext> => {

const mutationKey = ['logbooksUpdate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof logbooksUpdate>>, {id: string;data: DetectorLogbookRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  logbooksUpdate(id,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type LogbooksUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof logbooksUpdate>>>
    export type LogbooksUpdateMutationBody = DetectorLogbookRequest
    export type LogbooksUpdateMutationError = AxiosError<unknown>

    export const useLogbooksUpdate = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof logbooksUpdate>>, TError,{id: string;data: DetectorLogbookRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof logbooksUpdate>>,
        TError,
        {id: string;data: DetectorLogbookRequest},
        TContext
      > => {

      const mutationOptions = getLogbooksUpdateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Partially update a logbook entry.
 */
export const logbooksPartialUpdate = (
    id: string,
    patchedDetectorLogbookRequest: PatchedDetectorLogbookRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<DetectorLogbook>> => {
    
    
    return axios.default.patch(
      `/api/logbooks/${id}/`,
      patchedDetectorLogbookRequest,options
    );
  }



export const getLogbooksPartialUpdateMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof logbooksPartialUpdate>>, TError,{id: string;data: PatchedDetectorLogbookRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof logbooksPartialUpdate>>, TError,{id: string;data: PatchedDetectorLogbookRequest}, TContext> => {

const mutationKey = ['logbooksPartialUpdate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof logbooksPartialUpdate>>, {id: string;data: PatchedDetectorLogbookRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  logbooksPartialUpdate(id,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type LogbooksPartialUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof logbooksPartialUpdate>>>
    export type LogbooksPartialUpdateMutationBody = PatchedDetectorLogbookRequest
    export type LogbooksPartialUpdateMutationError = AxiosError<unknown>

    export const useLogbooksPartialUpdate = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof logbooksPartialUpdate>>, TError,{id: string;data: PatchedDetectorLogbookRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof logbooksPartialUpdate>>,
        TError,
        {id: string;data: PatchedDetectorLogbookRequest},
        TContext
      > => {

      const mutationOptions = getLogbooksPartialUpdateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Soft-delete a logbook entry.
 */
export const logbooksDestroy = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.delete(
      `/api/logbooks/${id}/`,options
    );
  }



export const getLogbooksDestroyMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof logbooksDestroy>>, TError,{id: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof logbooksDestroy>>, TError,{id: string}, TContext> => {

const mutationKey = ['logbooksDestroy'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof logbooksDestroy>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  logbooksDestroy(id,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type LogbooksDestroyMutationResult = NonNullable<Awaited<ReturnType<typeof logbooksDestroy>>>
    
    export type LogbooksDestroyMutationError = AxiosError<unknown>

    export const useLogbooksDestroy = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof logbooksDestroy>>, TError,{id: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof logbooksDestroy>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getLogbooksDestroyMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    