"""
Django settings for DOSPORTAL project.

Generated by 'django-admin startproject' using Django 4.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "SECRET_KEY", "django-insecure-)&9q7=6szljptu&2a11rq1k-ofhz1s$nxk&t+f=3xk74(vq4jq"
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False") == "True"

ALLOWED_HOSTS = os.getenv(
    "ALLOWED_HOSTS", "localhost,127.0.0.1,0.0.0.0,backend"
).split(",")

# Site URL configuration
SITE_URL = os.getenv("SITE_URL", "http://localhost:8080")
SITE_PORT = os.getenv("SITE_PORT", "8080")

# Trust X-Forwarded headers from nginx proxy
USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True

CSRF_TRUSTED_ORIGINS = os.getenv(
    "CSRF_TRUSTED_ORIGINS",
    "https://portal.dos.ust.cz,https://eurados-demo.dos.ust.cz,http://localhost:5173,http://127.0.0.1:5173,http://frontend:5173",
).split(",")

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.postgres",
    "django.contrib.gis",
    # 'bootstrap5',
    "django_bootstrap5",
    #'background_task',
    #'django_json_widget',
    "rest_framework",
    "rest_framework.authtoken",
    "corsheaders",
    "jquery",
    "import_export",
    "django_select2",
    "martor",
    "django_tables2",
    "DOSPORTAL",
    "django_q",
    "crispy_forms",
    "crispy_bootstrap5",
    "django_gravatar",
    "markdownx",
    "guardian",
    "prettyjson",
    "storages",
    "drf_spectacular",
    #  'organizations',
]

MARKDOWNX_MARKDOWN_EXTENSIONS = ["markdown.extensions.extra"]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

ROOT_URLCONF = "DOSPORTAL.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "DOSPORTAL.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'db.sqlite3',
    # }
    "default": {
        # "ENGINE": "django.db.backends.postgresql",
        "ENGINE": "django.contrib.gis.db.backends.postgis",
        "NAME": os.getenv("POSTGRES_DB", "dosportal"),
        "USER": os.getenv("POSTGRES_USER", "dosportal_user"),
        "PASSWORD": os.getenv("POSTGRES_PASSWORD", "dosportal_password"),
        "HOST": os.getenv("POSTGRES_HOST", "db_dosportal"),
        "PORT": os.getenv("POSTGRES_PORT", "5432"),
    }
}


AUTHENTICATION_BACKENDS = (
    "django.contrib.auth.backends.ModelBackend",  # this is default
    "guardian.backends.ObjectPermissionBackend",
)

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

LOGIN_REDIRECT_URL = "home"
LOGOUT_REDIRECT_URL = "home"

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# CORS Configuration - React frontend
CORS_ORIGIN_ALLOW_ALL = False
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://frontend:3000",
    "http://0.0.0.0:3000",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://frontend:5173",
    "http://0.0.0.0:5173",
    "http://localhost:8080",
    "http://127.0.0.1:8080",
]

CORS_ALLOW_CREDENTIALS = True

STATICFILES_DIRS = [
    Path(__file__).resolve().parent / "static",
]

STATIC_ROOT = BASE_DIR / "static"
STATIC_URL = "static/"


# MinIO Configuration (S3-compatible)
AWS_ACCESS_KEY_ID = os.getenv("MINIO_ACCESS_KEY", "minioadmin")
AWS_SECRET_ACCESS_KEY = os.getenv("MINIO_SECRET_KEY", "minioadmin")
AWS_STORAGE_BUCKET_NAME = os.getenv("MINIO_BUCKET_NAME", "dosportal-media")
AWS_S3_ENDPOINT_URL = os.getenv("MINIO_ENDPOINT_URL", "http://minio:9000")
AWS_S3_REGION_NAME = os.getenv("MINIO_REGION", "us-east-1")

# Private bucket with pre-signed URLs
AWS_DEFAULT_ACL = None  # No public ACL
AWS_S3_FILE_OVERWRITE = False
AWS_QUERYSTRING_AUTH = True  # Use pre-signed URLs
AWS_QUERYSTRING_EXPIRE = 3600  # URLs expire after 1 hour (in seconds)
AWS_S3_SIGNATURE_VERSION = "s3v4"
AWS_S3_ADDRESSING_STYLE = os.getenv("AWS_S3_ADDRESSING_STYLE", "path")

# Django 6+ storage configuration
STORAGES = {
    "default": {
        "BACKEND": "DOSPORTAL.storage_backends.MinIOMediaStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# Store public URL for custom storage backend (used by custom storage to rewrite host)
MINIO_PUBLIC_URL = os.getenv("MINIO_PUBLIC_URL")
# For presigned URLs, do not set MEDIA_URL; admin and templates should use file.url
MEDIA_URL = None



REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.DjangoModelPermissionsOrAnonReadOnly"
    ],
}

SPECTACULAR_SETTINGS = {
    "TITLE": "DOSPORTAL API",
    "DESCRIPTION": "API Documentation for DOSPORTAL",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "COMPONENT_SPLIT_REQUEST": True,
    "SCHEMA_PATH_PREFIX": r"/api/",
    "SWAGGER_UI_SETTINGS": {
        "deepLinking": True,
        "persistAuthorization": True,
        "displayOperationId": True,
        "filter": True,
    },
    "TAGS": [
        {"name": "Authentication", "description": "User authentication endpoints"},
        {
            "name": "Organizations",
            "description": "Organization and membership management",
        },
        {"name": "Detectors", "description": "Radiation detector management"},
        {"name": "Measurements", "description": "Measurement data operations"},
    ],
}

DJANGO_TABLES2_TEMPLATE = "django_tables2/bootstrap5-responsive.html"

DJANGO_TABLES2_TABLE_ATTRS = {
    "class": "table table-hover",
    "thead": {
        "class": "table-light",
    },
}

MARTOR_THEME = "bootstrap"
MARTOR_ENABLE_CONFIGS = {
    "emoji": "true",  # to enable/disable emoji icons.
    "imgur": "false",  # to enable/disable imgur/custom uploader.
    "mention": "false",  # to enable/disable mention
    "jquery": "true",  # to include/revoke jquery (require for admin default django)
    "living": "false",  # to enable/disable live updates in preview
    "spellcheck": "false",  # to enable/disable spellcheck in form textareas
    "hljs": "true",  # to enable/disable hljs highlighting in preview
}


MARTOR_TOOLBAR_BUTTONS = [
    "bold",
    "italic",
    "horizontal",
    "heading",
    "pre-code",
    "blockquote",
    "unordered-list",
    "ordered-list",
    "link",
    "image-link",
    "image-upload",
    "emoji",
    "direct-mention",
    "toggle-maximize",
    "help",
]
MARTOR_ENABLE_LABEL = False


Q_CLUSTER = {
    "name": "Worker",
    "workers": 4,
    "timeout": 60,
    "retry": 90,
    "recycle": 500,
    "compress": True,
    #'save_limit': 250,
    #'queue_limit': 500,
    "cpu_affinity": 1,
    "label": "Async dosportal worker",
    #'orm': 'default',
    "redis": {
        "host": os.getenv("REDIS_HOST", "redis"),
        "port": 6379,
        "db": 0,
    },
}
