/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * DOSPORTAL API
 * API Documentation for DOSPORTAL
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  PaginatedSpectralRecordArtifactList,
  PaginatedSpectralRecordList,
  SpectralRecord,
  SpectralRecordArtifact,
  SpectralRecordArtifactsListParams,
  SpectralRecordCreate,
  SpectralRecordCreateRequest,
  SpectralRecordsListParams
} from '.././model';





/**
 * List spectral record artifacts accessible to the current user.
 */
export const spectralRecordArtifactsList = (
    params?: SpectralRecordArtifactsListParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PaginatedSpectralRecordArtifactList>> => {
    
    
    return axios.default.get(
      `/api/spectral-record-artifacts/`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getSpectralRecordArtifactsListQueryKey = (params?: SpectralRecordArtifactsListParams,) => {
    return [
    `/api/spectral-record-artifacts/`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getSpectralRecordArtifactsListQueryOptions = <TData = Awaited<ReturnType<typeof spectralRecordArtifactsList>>, TError = AxiosError<unknown>>(params?: SpectralRecordArtifactsListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof spectralRecordArtifactsList>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSpectralRecordArtifactsListQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof spectralRecordArtifactsList>>> = ({ signal }) => spectralRecordArtifactsList(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof spectralRecordArtifactsList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SpectralRecordArtifactsListQueryResult = NonNullable<Awaited<ReturnType<typeof spectralRecordArtifactsList>>>
export type SpectralRecordArtifactsListQueryError = AxiosError<unknown>


export function useSpectralRecordArtifactsList<TData = Awaited<ReturnType<typeof spectralRecordArtifactsList>>, TError = AxiosError<unknown>>(
 params: undefined |  SpectralRecordArtifactsListParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof spectralRecordArtifactsList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof spectralRecordArtifactsList>>,
          TError,
          Awaited<ReturnType<typeof spectralRecordArtifactsList>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSpectralRecordArtifactsList<TData = Awaited<ReturnType<typeof spectralRecordArtifactsList>>, TError = AxiosError<unknown>>(
 params?: SpectralRecordArtifactsListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof spectralRecordArtifactsList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof spectralRecordArtifactsList>>,
          TError,
          Awaited<ReturnType<typeof spectralRecordArtifactsList>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSpectralRecordArtifactsList<TData = Awaited<ReturnType<typeof spectralRecordArtifactsList>>, TError = AxiosError<unknown>>(
 params?: SpectralRecordArtifactsListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof spectralRecordArtifactsList>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useSpectralRecordArtifactsList<TData = Awaited<ReturnType<typeof spectralRecordArtifactsList>>, TError = AxiosError<unknown>>(
 params?: SpectralRecordArtifactsListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof spectralRecordArtifactsList>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSpectralRecordArtifactsListQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Get spectral record artifact detail.
 */
export const spectralRecordArtifactsRetrieve = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<SpectralRecordArtifact>> => {
    
    
    return axios.default.get(
      `/api/spectral-record-artifacts/${id}/`,options
    );
  }




export const getSpectralRecordArtifactsRetrieveQueryKey = (id?: string,) => {
    return [
    `/api/spectral-record-artifacts/${id}/`
    ] as const;
    }

    
export const getSpectralRecordArtifactsRetrieveQueryOptions = <TData = Awaited<ReturnType<typeof spectralRecordArtifactsRetrieve>>, TError = AxiosError<unknown>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof spectralRecordArtifactsRetrieve>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSpectralRecordArtifactsRetrieveQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof spectralRecordArtifactsRetrieve>>> = ({ signal }) => spectralRecordArtifactsRetrieve(id, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof spectralRecordArtifactsRetrieve>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SpectralRecordArtifactsRetrieveQueryResult = NonNullable<Awaited<ReturnType<typeof spectralRecordArtifactsRetrieve>>>
export type SpectralRecordArtifactsRetrieveQueryError = AxiosError<unknown>


export function useSpectralRecordArtifactsRetrieve<TData = Awaited<ReturnType<typeof spectralRecordArtifactsRetrieve>>, TError = AxiosError<unknown>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof spectralRecordArtifactsRetrieve>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof spectralRecordArtifactsRetrieve>>,
          TError,
          Awaited<ReturnType<typeof spectralRecordArtifactsRetrieve>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSpectralRecordArtifactsRetrieve<TData = Awaited<ReturnType<typeof spectralRecordArtifactsRetrieve>>, TError = AxiosError<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof spectralRecordArtifactsRetrieve>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof spectralRecordArtifactsRetrieve>>,
          TError,
          Awaited<ReturnType<typeof spectralRecordArtifactsRetrieve>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSpectralRecordArtifactsRetrieve<TData = Awaited<ReturnType<typeof spectralRecordArtifactsRetrieve>>, TError = AxiosError<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof spectralRecordArtifactsRetrieve>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useSpectralRecordArtifactsRetrieve<TData = Awaited<ReturnType<typeof spectralRecordArtifactsRetrieve>>, TError = AxiosError<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof spectralRecordArtifactsRetrieve>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSpectralRecordArtifactsRetrieveQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * List spectral records accessible to the current user.
 */
export const spectralRecordsList = (
    params?: SpectralRecordsListParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PaginatedSpectralRecordList>> => {
    
    
    return axios.default.get(
      `/api/spectral-records/`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getSpectralRecordsListQueryKey = (params?: SpectralRecordsListParams,) => {
    return [
    `/api/spectral-records/`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getSpectralRecordsListQueryOptions = <TData = Awaited<ReturnType<typeof spectralRecordsList>>, TError = AxiosError<unknown>>(params?: SpectralRecordsListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof spectralRecordsList>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSpectralRecordsListQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof spectralRecordsList>>> = ({ signal }) => spectralRecordsList(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof spectralRecordsList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SpectralRecordsListQueryResult = NonNullable<Awaited<ReturnType<typeof spectralRecordsList>>>
export type SpectralRecordsListQueryError = AxiosError<unknown>


export function useSpectralRecordsList<TData = Awaited<ReturnType<typeof spectralRecordsList>>, TError = AxiosError<unknown>>(
 params: undefined |  SpectralRecordsListParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof spectralRecordsList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof spectralRecordsList>>,
          TError,
          Awaited<ReturnType<typeof spectralRecordsList>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSpectralRecordsList<TData = Awaited<ReturnType<typeof spectralRecordsList>>, TError = AxiosError<unknown>>(
 params?: SpectralRecordsListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof spectralRecordsList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof spectralRecordsList>>,
          TError,
          Awaited<ReturnType<typeof spectralRecordsList>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSpectralRecordsList<TData = Awaited<ReturnType<typeof spectralRecordsList>>, TError = AxiosError<unknown>>(
 params?: SpectralRecordsListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof spectralRecordsList>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useSpectralRecordsList<TData = Awaited<ReturnType<typeof spectralRecordsList>>, TError = AxiosError<unknown>>(
 params?: SpectralRecordsListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof spectralRecordsList>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSpectralRecordsListQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Create a spectral record. Supply owner (org UUID) — user must be admin/owner of the organization.
 */
export const spectralRecordsCreate = (
    spectralRecordCreateRequest: SpectralRecordCreateRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<SpectralRecordCreate>> => {
    
    
    return axios.default.post(
      `/api/spectral-records/`,
      spectralRecordCreateRequest,options
    );
  }



export const getSpectralRecordsCreateMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof spectralRecordsCreate>>, TError,{data: SpectralRecordCreateRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof spectralRecordsCreate>>, TError,{data: SpectralRecordCreateRequest}, TContext> => {

const mutationKey = ['spectralRecordsCreate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof spectralRecordsCreate>>, {data: SpectralRecordCreateRequest}> = (props) => {
          const {data} = props ?? {};

          return  spectralRecordsCreate(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SpectralRecordsCreateMutationResult = NonNullable<Awaited<ReturnType<typeof spectralRecordsCreate>>>
    export type SpectralRecordsCreateMutationBody = SpectralRecordCreateRequest
    export type SpectralRecordsCreateMutationError = AxiosError<unknown>

    export const useSpectralRecordsCreate = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof spectralRecordsCreate>>, TError,{data: SpectralRecordCreateRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof spectralRecordsCreate>>,
        TError,
        {data: SpectralRecordCreateRequest},
        TContext
      > => {

      const mutationOptions = getSpectralRecordsCreateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Get spectral record detail.
 */
export const spectralRecordsRetrieve = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<SpectralRecord>> => {
    
    
    return axios.default.get(
      `/api/spectral-records/${id}/`,options
    );
  }




export const getSpectralRecordsRetrieveQueryKey = (id?: string,) => {
    return [
    `/api/spectral-records/${id}/`
    ] as const;
    }

    
export const getSpectralRecordsRetrieveQueryOptions = <TData = Awaited<ReturnType<typeof spectralRecordsRetrieve>>, TError = AxiosError<unknown>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof spectralRecordsRetrieve>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSpectralRecordsRetrieveQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof spectralRecordsRetrieve>>> = ({ signal }) => spectralRecordsRetrieve(id, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof spectralRecordsRetrieve>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SpectralRecordsRetrieveQueryResult = NonNullable<Awaited<ReturnType<typeof spectralRecordsRetrieve>>>
export type SpectralRecordsRetrieveQueryError = AxiosError<unknown>


export function useSpectralRecordsRetrieve<TData = Awaited<ReturnType<typeof spectralRecordsRetrieve>>, TError = AxiosError<unknown>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof spectralRecordsRetrieve>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof spectralRecordsRetrieve>>,
          TError,
          Awaited<ReturnType<typeof spectralRecordsRetrieve>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSpectralRecordsRetrieve<TData = Awaited<ReturnType<typeof spectralRecordsRetrieve>>, TError = AxiosError<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof spectralRecordsRetrieve>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof spectralRecordsRetrieve>>,
          TError,
          Awaited<ReturnType<typeof spectralRecordsRetrieve>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSpectralRecordsRetrieve<TData = Awaited<ReturnType<typeof spectralRecordsRetrieve>>, TError = AxiosError<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof spectralRecordsRetrieve>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useSpectralRecordsRetrieve<TData = Awaited<ReturnType<typeof spectralRecordsRetrieve>>, TError = AxiosError<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof spectralRecordsRetrieve>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSpectralRecordsRetrieveQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Soft-delete a spectral record (org admin/owner only).
 */
export const spectralRecordsDestroy = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.delete(
      `/api/spectral-records/${id}/`,options
    );
  }



export const getSpectralRecordsDestroyMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof spectralRecordsDestroy>>, TError,{id: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof spectralRecordsDestroy>>, TError,{id: string}, TContext> => {

const mutationKey = ['spectralRecordsDestroy'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof spectralRecordsDestroy>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  spectralRecordsDestroy(id,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SpectralRecordsDestroyMutationResult = NonNullable<Awaited<ReturnType<typeof spectralRecordsDestroy>>>
    
    export type SpectralRecordsDestroyMutationError = AxiosError<unknown>

    export const useSpectralRecordsDestroy = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof spectralRecordsDestroy>>, TError,{id: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof spectralRecordsDestroy>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getSpectralRecordsDestroyMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Get counts-per-second evolution over time from Parquet artifact.
 */
export const spectralRecordsEvolutionRetrieve = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<SpectralRecord>> => {
    
    
    return axios.default.get(
      `/api/spectral-records/${id}/evolution/`,options
    );
  }




export const getSpectralRecordsEvolutionRetrieveQueryKey = (id?: string,) => {
    return [
    `/api/spectral-records/${id}/evolution/`
    ] as const;
    }

    
export const getSpectralRecordsEvolutionRetrieveQueryOptions = <TData = Awaited<ReturnType<typeof spectralRecordsEvolutionRetrieve>>, TError = AxiosError<unknown>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof spectralRecordsEvolutionRetrieve>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSpectralRecordsEvolutionRetrieveQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof spectralRecordsEvolutionRetrieve>>> = ({ signal }) => spectralRecordsEvolutionRetrieve(id, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof spectralRecordsEvolutionRetrieve>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SpectralRecordsEvolutionRetrieveQueryResult = NonNullable<Awaited<ReturnType<typeof spectralRecordsEvolutionRetrieve>>>
export type SpectralRecordsEvolutionRetrieveQueryError = AxiosError<unknown>


export function useSpectralRecordsEvolutionRetrieve<TData = Awaited<ReturnType<typeof spectralRecordsEvolutionRetrieve>>, TError = AxiosError<unknown>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof spectralRecordsEvolutionRetrieve>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof spectralRecordsEvolutionRetrieve>>,
          TError,
          Awaited<ReturnType<typeof spectralRecordsEvolutionRetrieve>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSpectralRecordsEvolutionRetrieve<TData = Awaited<ReturnType<typeof spectralRecordsEvolutionRetrieve>>, TError = AxiosError<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof spectralRecordsEvolutionRetrieve>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof spectralRecordsEvolutionRetrieve>>,
          TError,
          Awaited<ReturnType<typeof spectralRecordsEvolutionRetrieve>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSpectralRecordsEvolutionRetrieve<TData = Awaited<ReturnType<typeof spectralRecordsEvolutionRetrieve>>, TError = AxiosError<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof spectralRecordsEvolutionRetrieve>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useSpectralRecordsEvolutionRetrieve<TData = Awaited<ReturnType<typeof spectralRecordsEvolutionRetrieve>>, TError = AxiosError<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof spectralRecordsEvolutionRetrieve>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSpectralRecordsEvolutionRetrieveQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Get energy/channel spectrum (sum over all exposures) from Parquet artifact.
 */
export const spectralRecordsSpectrumRetrieve = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<SpectralRecord>> => {
    
    
    return axios.default.get(
      `/api/spectral-records/${id}/spectrum/`,options
    );
  }




export const getSpectralRecordsSpectrumRetrieveQueryKey = (id?: string,) => {
    return [
    `/api/spectral-records/${id}/spectrum/`
    ] as const;
    }

    
export const getSpectralRecordsSpectrumRetrieveQueryOptions = <TData = Awaited<ReturnType<typeof spectralRecordsSpectrumRetrieve>>, TError = AxiosError<unknown>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof spectralRecordsSpectrumRetrieve>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSpectralRecordsSpectrumRetrieveQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof spectralRecordsSpectrumRetrieve>>> = ({ signal }) => spectralRecordsSpectrumRetrieve(id, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof spectralRecordsSpectrumRetrieve>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SpectralRecordsSpectrumRetrieveQueryResult = NonNullable<Awaited<ReturnType<typeof spectralRecordsSpectrumRetrieve>>>
export type SpectralRecordsSpectrumRetrieveQueryError = AxiosError<unknown>


export function useSpectralRecordsSpectrumRetrieve<TData = Awaited<ReturnType<typeof spectralRecordsSpectrumRetrieve>>, TError = AxiosError<unknown>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof spectralRecordsSpectrumRetrieve>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof spectralRecordsSpectrumRetrieve>>,
          TError,
          Awaited<ReturnType<typeof spectralRecordsSpectrumRetrieve>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSpectralRecordsSpectrumRetrieve<TData = Awaited<ReturnType<typeof spectralRecordsSpectrumRetrieve>>, TError = AxiosError<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof spectralRecordsSpectrumRetrieve>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof spectralRecordsSpectrumRetrieve>>,
          TError,
          Awaited<ReturnType<typeof spectralRecordsSpectrumRetrieve>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSpectralRecordsSpectrumRetrieve<TData = Awaited<ReturnType<typeof spectralRecordsSpectrumRetrieve>>, TError = AxiosError<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof spectralRecordsSpectrumRetrieve>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useSpectralRecordsSpectrumRetrieve<TData = Awaited<ReturnType<typeof spectralRecordsSpectrumRetrieve>>, TError = AxiosError<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof spectralRecordsSpectrumRetrieve>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSpectralRecordsSpectrumRetrieveQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




