/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * DOSPORTAL API
 * API Documentation for DOSPORTAL
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  MeasurementCreate,
  MeasurementCreateRequest,
  MeasurementSegment,
  MeasurementSegmentRequest,
  MeasurementSegmentsListParams,
  Measurements,
  MeasurementsListParams,
  MeasurementsRequest,
  PaginatedMeasurementSegmentList,
  PaginatedMeasurementsList,
  PatchedMeasurementSegmentRequest
} from '.././model';





/**
 * List measurement segments accessible to the current user. Filter by ?measurement=<id>.
 */
export const measurementSegmentsList = (
    params?: MeasurementSegmentsListParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PaginatedMeasurementSegmentList>> => {
    
    
    return axios.default.get(
      `/api/measurement-segments/`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getMeasurementSegmentsListQueryKey = (params?: MeasurementSegmentsListParams,) => {
    return [
    `/api/measurement-segments/`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getMeasurementSegmentsListQueryOptions = <TData = Awaited<ReturnType<typeof measurementSegmentsList>>, TError = AxiosError<unknown>>(params?: MeasurementSegmentsListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof measurementSegmentsList>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getMeasurementSegmentsListQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof measurementSegmentsList>>> = ({ signal }) => measurementSegmentsList(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof measurementSegmentsList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type MeasurementSegmentsListQueryResult = NonNullable<Awaited<ReturnType<typeof measurementSegmentsList>>>
export type MeasurementSegmentsListQueryError = AxiosError<unknown>


export function useMeasurementSegmentsList<TData = Awaited<ReturnType<typeof measurementSegmentsList>>, TError = AxiosError<unknown>>(
 params: undefined |  MeasurementSegmentsListParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof measurementSegmentsList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof measurementSegmentsList>>,
          TError,
          Awaited<ReturnType<typeof measurementSegmentsList>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useMeasurementSegmentsList<TData = Awaited<ReturnType<typeof measurementSegmentsList>>, TError = AxiosError<unknown>>(
 params?: MeasurementSegmentsListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof measurementSegmentsList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof measurementSegmentsList>>,
          TError,
          Awaited<ReturnType<typeof measurementSegmentsList>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useMeasurementSegmentsList<TData = Awaited<ReturnType<typeof measurementSegmentsList>>, TError = AxiosError<unknown>>(
 params?: MeasurementSegmentsListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof measurementSegmentsList>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useMeasurementSegmentsList<TData = Awaited<ReturnType<typeof measurementSegmentsList>>, TError = AxiosError<unknown>>(
 params?: MeasurementSegmentsListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof measurementSegmentsList>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getMeasurementSegmentsListQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Create a measurement segment. User must be a member of the measurement's organization.
 */
export const measurementSegmentsCreate = (
    measurementSegmentRequest: MeasurementSegmentRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<MeasurementSegment>> => {
    
    
    return axios.default.post(
      `/api/measurement-segments/`,
      measurementSegmentRequest,options
    );
  }



export const getMeasurementSegmentsCreateMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof measurementSegmentsCreate>>, TError,{data: MeasurementSegmentRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof measurementSegmentsCreate>>, TError,{data: MeasurementSegmentRequest}, TContext> => {

const mutationKey = ['measurementSegmentsCreate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof measurementSegmentsCreate>>, {data: MeasurementSegmentRequest}> = (props) => {
          const {data} = props ?? {};

          return  measurementSegmentsCreate(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type MeasurementSegmentsCreateMutationResult = NonNullable<Awaited<ReturnType<typeof measurementSegmentsCreate>>>
    export type MeasurementSegmentsCreateMutationBody = MeasurementSegmentRequest
    export type MeasurementSegmentsCreateMutationError = AxiosError<unknown>

    export const useMeasurementSegmentsCreate = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof measurementSegmentsCreate>>, TError,{data: MeasurementSegmentRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof measurementSegmentsCreate>>,
        TError,
        {data: MeasurementSegmentRequest},
        TContext
      > => {

      const mutationOptions = getMeasurementSegmentsCreateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Get measurement segment detail.
 */
export const measurementSegmentsRetrieve = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<MeasurementSegment>> => {
    
    
    return axios.default.get(
      `/api/measurement-segments/${id}/`,options
    );
  }




export const getMeasurementSegmentsRetrieveQueryKey = (id?: string,) => {
    return [
    `/api/measurement-segments/${id}/`
    ] as const;
    }

    
export const getMeasurementSegmentsRetrieveQueryOptions = <TData = Awaited<ReturnType<typeof measurementSegmentsRetrieve>>, TError = AxiosError<unknown>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof measurementSegmentsRetrieve>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getMeasurementSegmentsRetrieveQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof measurementSegmentsRetrieve>>> = ({ signal }) => measurementSegmentsRetrieve(id, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof measurementSegmentsRetrieve>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type MeasurementSegmentsRetrieveQueryResult = NonNullable<Awaited<ReturnType<typeof measurementSegmentsRetrieve>>>
export type MeasurementSegmentsRetrieveQueryError = AxiosError<unknown>


export function useMeasurementSegmentsRetrieve<TData = Awaited<ReturnType<typeof measurementSegmentsRetrieve>>, TError = AxiosError<unknown>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof measurementSegmentsRetrieve>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof measurementSegmentsRetrieve>>,
          TError,
          Awaited<ReturnType<typeof measurementSegmentsRetrieve>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useMeasurementSegmentsRetrieve<TData = Awaited<ReturnType<typeof measurementSegmentsRetrieve>>, TError = AxiosError<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof measurementSegmentsRetrieve>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof measurementSegmentsRetrieve>>,
          TError,
          Awaited<ReturnType<typeof measurementSegmentsRetrieve>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useMeasurementSegmentsRetrieve<TData = Awaited<ReturnType<typeof measurementSegmentsRetrieve>>, TError = AxiosError<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof measurementSegmentsRetrieve>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useMeasurementSegmentsRetrieve<TData = Awaited<ReturnType<typeof measurementSegmentsRetrieve>>, TError = AxiosError<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof measurementSegmentsRetrieve>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getMeasurementSegmentsRetrieveQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Partially update a segment (e.g. time_from, time_to, position).
 */
export const measurementSegmentsPartialUpdate = (
    id: string,
    patchedMeasurementSegmentRequest: PatchedMeasurementSegmentRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<MeasurementSegment>> => {
    
    
    return axios.default.patch(
      `/api/measurement-segments/${id}/`,
      patchedMeasurementSegmentRequest,options
    );
  }



export const getMeasurementSegmentsPartialUpdateMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof measurementSegmentsPartialUpdate>>, TError,{id: string;data: PatchedMeasurementSegmentRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof measurementSegmentsPartialUpdate>>, TError,{id: string;data: PatchedMeasurementSegmentRequest}, TContext> => {

const mutationKey = ['measurementSegmentsPartialUpdate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof measurementSegmentsPartialUpdate>>, {id: string;data: PatchedMeasurementSegmentRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  measurementSegmentsPartialUpdate(id,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type MeasurementSegmentsPartialUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof measurementSegmentsPartialUpdate>>>
    export type MeasurementSegmentsPartialUpdateMutationBody = PatchedMeasurementSegmentRequest
    export type MeasurementSegmentsPartialUpdateMutationError = AxiosError<unknown>

    export const useMeasurementSegmentsPartialUpdate = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof measurementSegmentsPartialUpdate>>, TError,{id: string;data: PatchedMeasurementSegmentRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof measurementSegmentsPartialUpdate>>,
        TError,
        {id: string;data: PatchedMeasurementSegmentRequest},
        TContext
      > => {

      const mutationOptions = getMeasurementSegmentsPartialUpdateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Delete a measurement segment. Only accessible to the measurement author or org admin/owner.
 */
export const measurementSegmentsDestroy = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.delete(
      `/api/measurement-segments/${id}/`,options
    );
  }



export const getMeasurementSegmentsDestroyMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof measurementSegmentsDestroy>>, TError,{id: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof measurementSegmentsDestroy>>, TError,{id: string}, TContext> => {

const mutationKey = ['measurementSegmentsDestroy'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof measurementSegmentsDestroy>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  measurementSegmentsDestroy(id,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type MeasurementSegmentsDestroyMutationResult = NonNullable<Awaited<ReturnType<typeof measurementSegmentsDestroy>>>
    
    export type MeasurementSegmentsDestroyMutationError = AxiosError<unknown>

    export const useMeasurementSegmentsDestroy = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof measurementSegmentsDestroy>>, TError,{id: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof measurementSegmentsDestroy>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getMeasurementSegmentsDestroyMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * List measurements accessible to the current user.
 */
export const measurementsList = (
    params?: MeasurementsListParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PaginatedMeasurementsList>> => {
    
    
    return axios.default.get(
      `/api/measurements/`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getMeasurementsListQueryKey = (params?: MeasurementsListParams,) => {
    return [
    `/api/measurements/`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getMeasurementsListQueryOptions = <TData = Awaited<ReturnType<typeof measurementsList>>, TError = AxiosError<unknown>>(params?: MeasurementsListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof measurementsList>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getMeasurementsListQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof measurementsList>>> = ({ signal }) => measurementsList(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof measurementsList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type MeasurementsListQueryResult = NonNullable<Awaited<ReturnType<typeof measurementsList>>>
export type MeasurementsListQueryError = AxiosError<unknown>


export function useMeasurementsList<TData = Awaited<ReturnType<typeof measurementsList>>, TError = AxiosError<unknown>>(
 params: undefined |  MeasurementsListParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof measurementsList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof measurementsList>>,
          TError,
          Awaited<ReturnType<typeof measurementsList>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useMeasurementsList<TData = Awaited<ReturnType<typeof measurementsList>>, TError = AxiosError<unknown>>(
 params?: MeasurementsListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof measurementsList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof measurementsList>>,
          TError,
          Awaited<ReturnType<typeof measurementsList>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useMeasurementsList<TData = Awaited<ReturnType<typeof measurementsList>>, TError = AxiosError<unknown>>(
 params?: MeasurementsListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof measurementsList>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useMeasurementsList<TData = Awaited<ReturnType<typeof measurementsList>>, TError = AxiosError<unknown>>(
 params?: MeasurementsListParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof measurementsList>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getMeasurementsListQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Create a measurement. Supply owner_id to assign to an organization (user must be a member).
 */
export const measurementsCreate = (
    measurementCreateRequest: MeasurementCreateRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<MeasurementCreate>> => {
    
    
    return axios.default.post(
      `/api/measurements/`,
      measurementCreateRequest,options
    );
  }



export const getMeasurementsCreateMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof measurementsCreate>>, TError,{data: MeasurementCreateRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof measurementsCreate>>, TError,{data: MeasurementCreateRequest}, TContext> => {

const mutationKey = ['measurementsCreate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof measurementsCreate>>, {data: MeasurementCreateRequest}> = (props) => {
          const {data} = props ?? {};

          return  measurementsCreate(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type MeasurementsCreateMutationResult = NonNullable<Awaited<ReturnType<typeof measurementsCreate>>>
    export type MeasurementsCreateMutationBody = MeasurementCreateRequest
    export type MeasurementsCreateMutationError = AxiosError<unknown>

    export const useMeasurementsCreate = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof measurementsCreate>>, TError,{data: MeasurementCreateRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof measurementsCreate>>,
        TError,
        {data: MeasurementCreateRequest},
        TContext
      > => {

      const mutationOptions = getMeasurementsCreateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Get measurement detail by ID.
 */
export const measurementsRetrieve = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Measurements>> => {
    
    
    return axios.default.get(
      `/api/measurements/${id}/`,options
    );
  }




export const getMeasurementsRetrieveQueryKey = (id?: string,) => {
    return [
    `/api/measurements/${id}/`
    ] as const;
    }

    
export const getMeasurementsRetrieveQueryOptions = <TData = Awaited<ReturnType<typeof measurementsRetrieve>>, TError = AxiosError<unknown>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof measurementsRetrieve>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getMeasurementsRetrieveQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof measurementsRetrieve>>> = ({ signal }) => measurementsRetrieve(id, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof measurementsRetrieve>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type MeasurementsRetrieveQueryResult = NonNullable<Awaited<ReturnType<typeof measurementsRetrieve>>>
export type MeasurementsRetrieveQueryError = AxiosError<unknown>


export function useMeasurementsRetrieve<TData = Awaited<ReturnType<typeof measurementsRetrieve>>, TError = AxiosError<unknown>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof measurementsRetrieve>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof measurementsRetrieve>>,
          TError,
          Awaited<ReturnType<typeof measurementsRetrieve>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useMeasurementsRetrieve<TData = Awaited<ReturnType<typeof measurementsRetrieve>>, TError = AxiosError<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof measurementsRetrieve>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof measurementsRetrieve>>,
          TError,
          Awaited<ReturnType<typeof measurementsRetrieve>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useMeasurementsRetrieve<TData = Awaited<ReturnType<typeof measurementsRetrieve>>, TError = AxiosError<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof measurementsRetrieve>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useMeasurementsRetrieve<TData = Awaited<ReturnType<typeof measurementsRetrieve>>, TError = AxiosError<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof measurementsRetrieve>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getMeasurementsRetrieveQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Soft-delete a measurement (author or org admin/owner only).
 */
export const measurementsDestroy = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.delete(
      `/api/measurements/${id}/`,options
    );
  }



export const getMeasurementsDestroyMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof measurementsDestroy>>, TError,{id: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof measurementsDestroy>>, TError,{id: string}, TContext> => {

const mutationKey = ['measurementsDestroy'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof measurementsDestroy>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  measurementsDestroy(id,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type MeasurementsDestroyMutationResult = NonNullable<Awaited<ReturnType<typeof measurementsDestroy>>>
    
    export type MeasurementsDestroyMutationError = AxiosError<unknown>

    export const useMeasurementsDestroy = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof measurementsDestroy>>, TError,{id: string}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof measurementsDestroy>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getMeasurementsDestroyMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Get counts-per-second evolution over time from Parquet artifact.
 */
export const measurementsEvolutionRetrieve = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Measurements>> => {
    
    
    return axios.default.get(
      `/api/measurements/${id}/evolution/`,options
    );
  }




export const getMeasurementsEvolutionRetrieveQueryKey = (id?: string,) => {
    return [
    `/api/measurements/${id}/evolution/`
    ] as const;
    }

    
export const getMeasurementsEvolutionRetrieveQueryOptions = <TData = Awaited<ReturnType<typeof measurementsEvolutionRetrieve>>, TError = AxiosError<unknown>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof measurementsEvolutionRetrieve>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getMeasurementsEvolutionRetrieveQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof measurementsEvolutionRetrieve>>> = ({ signal }) => measurementsEvolutionRetrieve(id, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof measurementsEvolutionRetrieve>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type MeasurementsEvolutionRetrieveQueryResult = NonNullable<Awaited<ReturnType<typeof measurementsEvolutionRetrieve>>>
export type MeasurementsEvolutionRetrieveQueryError = AxiosError<unknown>


export function useMeasurementsEvolutionRetrieve<TData = Awaited<ReturnType<typeof measurementsEvolutionRetrieve>>, TError = AxiosError<unknown>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof measurementsEvolutionRetrieve>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof measurementsEvolutionRetrieve>>,
          TError,
          Awaited<ReturnType<typeof measurementsEvolutionRetrieve>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useMeasurementsEvolutionRetrieve<TData = Awaited<ReturnType<typeof measurementsEvolutionRetrieve>>, TError = AxiosError<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof measurementsEvolutionRetrieve>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof measurementsEvolutionRetrieve>>,
          TError,
          Awaited<ReturnType<typeof measurementsEvolutionRetrieve>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useMeasurementsEvolutionRetrieve<TData = Awaited<ReturnType<typeof measurementsEvolutionRetrieve>>, TError = AxiosError<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof measurementsEvolutionRetrieve>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useMeasurementsEvolutionRetrieve<TData = Awaited<ReturnType<typeof measurementsEvolutionRetrieve>>, TError = AxiosError<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof measurementsEvolutionRetrieve>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getMeasurementsEvolutionRetrieveQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Routes DELETE to soft_delete() instead of hard delete.
 */
export const measurementsFinalizeCreate = (
    id: string,
    measurementsRequest: MeasurementsRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Measurements>> => {
    
    
    return axios.default.post(
      `/api/measurements/${id}/finalize/`,
      measurementsRequest,options
    );
  }



export const getMeasurementsFinalizeCreateMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof measurementsFinalizeCreate>>, TError,{id: string;data: MeasurementsRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof measurementsFinalizeCreate>>, TError,{id: string;data: MeasurementsRequest}, TContext> => {

const mutationKey = ['measurementsFinalizeCreate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof measurementsFinalizeCreate>>, {id: string;data: MeasurementsRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  measurementsFinalizeCreate(id,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type MeasurementsFinalizeCreateMutationResult = NonNullable<Awaited<ReturnType<typeof measurementsFinalizeCreate>>>
    export type MeasurementsFinalizeCreateMutationBody = MeasurementsRequest
    export type MeasurementsFinalizeCreateMutationError = AxiosError<unknown>

    export const useMeasurementsFinalizeCreate = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof measurementsFinalizeCreate>>, TError,{id: string;data: MeasurementsRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof measurementsFinalizeCreate>>,
        TError,
        {id: string;data: MeasurementsRequest},
        TContext
      > => {

      const mutationOptions = getMeasurementsFinalizeCreateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Get energy/channel spectrum (sum over all exposures) from Parquet artifact.
 */
export const measurementsSpectrumRetrieve = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Measurements>> => {
    
    
    return axios.default.get(
      `/api/measurements/${id}/spectrum/`,options
    );
  }




export const getMeasurementsSpectrumRetrieveQueryKey = (id?: string,) => {
    return [
    `/api/measurements/${id}/spectrum/`
    ] as const;
    }

    
export const getMeasurementsSpectrumRetrieveQueryOptions = <TData = Awaited<ReturnType<typeof measurementsSpectrumRetrieve>>, TError = AxiosError<unknown>>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof measurementsSpectrumRetrieve>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getMeasurementsSpectrumRetrieveQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof measurementsSpectrumRetrieve>>> = ({ signal }) => measurementsSpectrumRetrieve(id, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof measurementsSpectrumRetrieve>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type MeasurementsSpectrumRetrieveQueryResult = NonNullable<Awaited<ReturnType<typeof measurementsSpectrumRetrieve>>>
export type MeasurementsSpectrumRetrieveQueryError = AxiosError<unknown>


export function useMeasurementsSpectrumRetrieve<TData = Awaited<ReturnType<typeof measurementsSpectrumRetrieve>>, TError = AxiosError<unknown>>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof measurementsSpectrumRetrieve>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof measurementsSpectrumRetrieve>>,
          TError,
          Awaited<ReturnType<typeof measurementsSpectrumRetrieve>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useMeasurementsSpectrumRetrieve<TData = Awaited<ReturnType<typeof measurementsSpectrumRetrieve>>, TError = AxiosError<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof measurementsSpectrumRetrieve>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof measurementsSpectrumRetrieve>>,
          TError,
          Awaited<ReturnType<typeof measurementsSpectrumRetrieve>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useMeasurementsSpectrumRetrieve<TData = Awaited<ReturnType<typeof measurementsSpectrumRetrieve>>, TError = AxiosError<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof measurementsSpectrumRetrieve>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useMeasurementsSpectrumRetrieve<TData = Awaited<ReturnType<typeof measurementsSpectrumRetrieve>>, TError = AxiosError<unknown>>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof measurementsSpectrumRetrieve>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getMeasurementsSpectrumRetrieveQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




