# Generated by Django 4.2.1 on 2023-06-05 08:02

import DOSPORTAL.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Detector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('sn', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=150, verbose_name='Detector name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DetectorManufacturer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='measurement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('time_start', models.DateTimeField(null=True, verbose_name='Measurement beginning time')),
                ('time_end', models.DateTimeField(null=True, verbose_name='Measurement beginning time')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Time of creation')),
                ('name', models.CharField(max_length=150, verbose_name='measurement name')),
                ('description', models.CharField(max_length=500, verbose_name='Measurement description')),
                ('measurement_type', models.CharField(verbose_name='Certain measurement type, enum')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='record',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('log_file', models.FileField(upload_to=DOSPORTAL.models.record.user_directory_path, verbose_name='File log')),
                ('time_start', models.DateTimeField(null=True, verbose_name='Measurement beginning time')),
                ('time_end', models.DateTimeField(null=True, verbose_name='Measurement beginning time')),
                ('detector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DOSPORTAL.detector')),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DOSPORTAL.measurement')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='detector',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DOSPORTAL.detectormanufacturer'),
        ),
    ]
