# Generated by Django 4.2.11 on 2024-03-27 10:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('DOSPORTAL', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpectrumData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('time_difference', models.DurationField(help_text='Time difference from the start of the measurement', null=True, verbose_name='Time difference')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spectrum_data', to='DOSPORTAL.trajectorypoint')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spectrum_data', to='DOSPORTAL.record')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
