# Generated by Django 4.2.11 on 2024-03-27 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOSPORTAL', '0002_spectrumdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='spectrumdata',
            name='spectrum',
            field=models.JSONField(default=[], help_text='Energy spectrum data as an array of integers', verbose_name='Spectrum data'),
            preserve_default=False,
        ),
    ]
