# Generated by Django 4.2.11 on 2024-03-27 10:52

import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion
from django.contrib.postgres.operations import HStoreExtension

class Migration(migrations.Migration):

    dependencies = [
        ('DOSPORTAL', '0003_spectrumdata_spectrum'),
    ]

    operations = [
        HStoreExtension(),
        migrations.AddField(
            model_name='spectrumdata',
            name='metadata',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, help_text='Additional metadata for the spectrum data', null=True, verbose_name='Metadata'),
        ),
        migrations.AddField(
            model_name='spectrumdata',
            name='particles',
            field=models.ImageField(blank=True, help_text='Particles detected in the spectrum', null=True, upload_to='', verbose_name='Particles'),
        ),
        migrations.AlterField(
            model_name='spectrumdata',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spectrum_data', to='DOSPORTAL.record', verbose_name='Record'),
        ),
    ]
