# Generated by Django 4.2.11 on 2024-03-29 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOSPORTAL', '0003_rename_metadatar_record_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='log_original_filename',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Original filename of log file'),
        ),
        migrations.AlterField(
            model_name='record',
            name='text',
            field=models.TextField(help_text='Text log from detector', verbose_name='Text log'),
        ),
    ]
