# Generated by Django 4.2.1 on 2023-06-05 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOSPORTAL', '0003_remove_detector_manufacturer_detectortype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='measurement_type',
            field=models.CharField(blank=True, choices=[('D', 'Debug measurement'), ('S', 'Static measurement'), ('M', 'Mobile measurement (ground)'), ('C', 'Civil airborne measurement'), ('A', 'Special airborne measurement')], default='S', help_text='Type of measurement', verbose_name='Certain measurement type, enum'),
        ),
    ]
