# Generated by Django 4.2.11 on 2024-03-27 10:54

import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOSPORTAL', '0004_spectrumdata_metadata_spectrumdata_particles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spectrumdata',
            name='metadata',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, default={}, help_text='Additional metadata for the spectrum data', null=True, verbose_name='Metadata'),
        ),
        migrations.AlterField(
            model_name='spectrumdata',
            name='particles',
            field=models.IntegerField(blank=True, help_text='Particles detected in the spectrum', null=True, verbose_name='Particles'),
        ),
    ]
