# Generated by Django 4.2.11 on 2024-03-29 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOSPORTAL', '0004_alter_record_log_original_filename_alter_record_text'),
    ]

    #operations = [
    #    migrations.AlterField(
    #        model_name='record',
    #        name='text',
    #        field=models.TextField(blank=True, help_text='Text log from detector', null=True, verbose_name='Text log'),
    #    ),
    #]


    operations = [
        migrations.AddField(
            model_name='record',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='text',
            field=models.TextField(blank=True, help_text='Text log from detector', null=True, verbose_name='Text log'),
        ),
    ]
