# Generated by Django 4.2.11 on 2024-03-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOSPORTAL', '0005_alter_spectrumdata_metadata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spectrumdata',
            name='integration',
            field=models.FloatField(blank=True, help_text='Duration of last exposition', null=True, verbose_name='Integration time'),
        ),
        migrations.AlterField(
            model_name='spectrumdata',
            name='spectrum',
            field=models.JSONField(default=[], help_text='Energy spectrum data as an array of integers', verbose_name='Spectrum data'),
        ),
    ]
