# Generated by Django 4.2.1 on 2023-06-05 17:18

import DOSPORTAL.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOSPORTAL', '0005_measurement_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='base_location_alt',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measurement',
            name='base_location_lat',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measurement',
            name='base_location_lon',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measurement',
            name='location_file',
            field=models.FileField(default=1, upload_to=DOSPORTAL.models.measurement.user_directory_path, verbose_name='File log'),
            preserve_default=False,
        ),
    ]
