# Generated by Django 4.2.11 on 2024-03-29 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DOSPORTAL', '0005_alter_record_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='text',
        ),
    ]
