# Generated by Django 4.2.1 on 2023-06-05 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DOSPORTAL', '0006_measurement_base_location_alt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='detector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DOSPORTAL.detector'),
        ),
    ]
