# Generated by Django 4.2.11 on 2024-03-27 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DOSPORTAL', '0006_spectrumdata_integration_alter_spectrumdata_spectrum'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
