# Generated by Django 4.2.11 on 2024-03-29 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOSPORTAL', '0006_remove_record_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='data_file',
            field=models.FileField(blank=True, help_text='Processed spectral file', null=True, upload_to='', verbose_name='Log file'),
        ),
    ]
