# Generated by Django 4.2.1 on 2023-06-05 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DOSPORTAL', '0007_alter_record_detector'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='log_filename',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record',
            name='measurement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='DOSPORTAL.measurement'),
        ),
    ]
