# Generated by Django 4.2.1 on 2023-06-05 22:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('DOSPORTAL', '0009_alter_measurement_base_location_alt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airports',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField()),
                ('code_iata', models.CharField(null=True, unique=True)),
                ('code_icao', models.CharField(null=True, unique=True)),
                ('lat', models.FloatField(null=True)),
                ('lon', models.FloatField(null=True)),
                ('alt', models.FloatField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('callsign', models.CharField()),
                ('land', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landing', to='DOSPORTAL.airports')),
                ('takeoff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='takeoff', to='DOSPORTAL.airports')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MeasurementDataFlight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='DOSPORTAL.flight')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='record',
            name='flight',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='record', to='DOSPORTAL.flight'),
        ),
    ]
