# Generated by Django 4.2.11 on 2024-04-04 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOSPORTAL', '0009_record_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectortype',
            name='Detector image',
            field=models.ImageField(blank=True, help_text='Detector image', null=True, upload_to='detector_images'),
        ),
    ]
