# Generated by Django 4.2.11 on 2024-04-04 22:32

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('DOSPORTAL', '0011_detectortype_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectortype',
            name='description',
            field=markdownx.models.MarkdownxField(blank=True, help_text='Detector description', verbose_name='Detector description'),
        ),
    ]
