# Generated by Django 4.2.2 on 2023-06-21 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOSPORTAL', '0012_alter_record_flight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='callsign',
            new_name='flight_number',
        ),
        migrations.AddField(
            model_name='flight',
            name='departure_time',
            field=models.DateTimeField(null=True, verbose_name='Scheduled departure time'),
        ),
        migrations.AlterUniqueTogether(
            name='flight',
            unique_together={('flight_number', 'departure_time')},
        ),
    ]
