# Generated by Django 4.2.2 on 2023-06-22 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DOSPORTAL', '0014_remove_record_flight_measurement_flight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='flight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='record', to='DOSPORTAL.flight', verbose_name='Reference na objekt s informacemi o letu'),
        ),
    ]
