# Generated by Django 4.2.11 on 2024-04-05 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOSPORTAL', '0014_alter_detector_data_alter_record_metadata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='time_tracked',
            field=models.BooleanField(default=False, help_text="When time is tracked, 'time_start' must be filled out", verbose_name='Is time tracked?'),
        ),
    ]
