# Generated by Django 4.2.11 on 2024-04-05 02:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOSPORTAL', '0015_record_time_tracked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='time_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2000, 1, 1, 0, 0), null=True, verbose_name='Measurement beginning time'),
        ),
    ]
