# Generated by Django 4.2.2 on 2023-06-23 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOSPORTAL', '0016_record_record_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airports',
            name='municipality',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='airports',
            name='web',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='record_type',
            field=models.CharField(choices=[('S', 'Spectral measurements'), ('L', 'Location')], default='S', help_text='Type of log file', verbose_name='Certain record type, enum'),
        ),
    ]
