# Generated by Django 4.2.11 on 2024-04-05 16:38

import DOSPORTAL.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOSPORTAL', '0016_alter_record_time_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='metadata_file',
            field=models.FileField(blank=True, help_text='Processed metadata file', null=True, upload_to=DOSPORTAL.models.Record.user_directory_path_data, verbose_name='Metadata file'),
        ),
    ]
