# Generated by Django 4.2.11 on 2024-04-06 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DOSPORTAL', '0017_record_metadata_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='calib',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='DOSPORTAL.detectorcalib'),
        ),
    ]
