# Generated by Django 4.2.11 on 2024-04-06 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DOSPORTAL', '0018_record_calib'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detector',
            name='calib',
        ),
    ]
