# Generated by Django 4.2.2 on 2023-06-23 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DOSPORTAL', '0018_detectorcalib'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detectorcalib',
            name='author',
        ),
    ]
