# Generated by Django 4.2.11 on 2024-04-06 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOSPORTAL', '0019_remove_detector_calib'),
    ]

    operations = [
        migrations.AddField(
            model_name='detector',
            name='Detector calibration',
            field=models.ManyToManyField(blank=True, help_text='Detector calibration', related_name='detectors', to='DOSPORTAL.detectorcalib'),
        ),
    ]
