# Generated by Django 4.2.2 on 2023-06-23 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DOSPORTAL', '0019_remove_detectorcalib_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='detector',
            name='calib',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='DOSPORTAL.detectorcalib'),
        ),
    ]
