# Generated by Django 4.2.11 on 2024-04-06 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DOSPORTAL', '0020_detector_detector_calibration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detectorcalib',
            name='cabib',
        ),
    ]
