# Generated by Django 4.2.2 on 2023-06-24 01:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('DOSPORTAL', '0020_detector_calib'),
    ]

    operations = [
        migrations.CreateModel(
            name='measurement_campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=150, verbose_name='measurement name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='detector',
            name='calib',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DOSPORTAL.detectorcalib'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='compaings',
            field=models.ManyToManyField(related_name='Campaigns', to='DOSPORTAL.measurement_campaign'),
        ),
    ]
