# Generated by Django 4.2.11 on 2024-04-06 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOSPORTAL', '0021_remove_detectorcalib_cabib'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detector',
            name='Detector calibration',
        ),
        migrations.AddField(
            model_name='detector',
            name='calibration',
            field=models.ManyToManyField(blank=True, help_text='Detector calibration', to='DOSPORTAL.detectorcalib'),
        ),
    ]
