# Generated by Django 4.2.11 on 2024-04-06 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DOSPORTAL', '0022_remove_detector_detector_calibration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detector',
            old_name='calibration',
            new_name='calib',
        ),
    ]
