# Generated by Django 4.2.2 on 2023-06-24 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOSPORTAL', '0022_alter_measurement_campaign_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectorcalib',
            name='cabib',
            field=models.JSONField(verbose_name='Slozky kalibrace, json'),
        ),
    ]
