# Generated by Django 4.2.11 on 2024-04-06 22:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DOSPORTAL', '0023_rename_calibration_detector_calib'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detector',
            name='calib',
        ),
        migrations.AddField(
            model_name='detectorcalib',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='DetectorToCalibration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calib', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DOSPORTAL.detectorcalib')),
                ('detector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DOSPORTAL.detector')),
            ],
            options={
                'ordering': ['calib__created'],
            },
        ),
    ]
