# Generated by Django 4.2.11 on 2024-04-06 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOSPORTAL', '0024_remove_detector_calib_detectorcalib_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detector',
            name='calib',
            field=models.ManyToManyField(blank=True, help_text='Detector calibration', through='DOSPORTAL.DetectorToCalibration', to='DOSPORTAL.detectorcalib'),
        ),
    ]
