# Generated by Django 4.2.11 on 2024-04-06 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DOSPORTAL', '0025_detector_calib'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detector',
            name='calib',
        ),
        migrations.DeleteModel(
            name='DetectorToCalibration',
        ),
    ]
