# Generated by Django 4.2.11 on 2024-04-06 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOSPORTAL', '0026_remove_detector_calib_delete_detectortocalibration'),
    ]

    operations = [
        migrations.AddField(
            model_name='detector',
            name='calib',
            field=models.ManyToManyField(blank=True, help_text='Detector calibration', to='DOSPORTAL.detectorcalib'),
        ),
    ]
