# Generated by Django 4.2.2 on 2023-06-25 07:55

from django.db import migrations
import martor.models


class Migration(migrations.Migration):

    dependencies = [
        ('DOSPORTAL', '0026_detectorlogbook_delete_detectorlogblock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='description',
            field=martor.models.MartorField(verbose_name='Measurement description'),
        ),
    ]
