# Generated by Django 4.2.11 on 2024-04-06 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOSPORTAL', '0027_detector_calib'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='time_of_interenst_end',
            field=models.DurationField(blank=True, default=None, null=True, verbose_name='Time of interest end'),
        ),
        migrations.AddField(
            model_name='record',
            name='time_of_interenst_start',
            field=models.DurationField(blank=True, default=None, null=True, verbose_name='Time of interest start'),
        ),
    ]
