# Generated by Django 4.2.11 on 2024-04-06 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DOSPORTAL', '0028_record_time_of_interenst_end_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='time_of_interenst_end',
            new_name='time_of_interest_end',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='time_of_interenst_start',
            new_name='time_of_interest_start',
        ),
    ]
