# Generated by Django 4.2.11 on 2024-04-07 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DOSPORTAL', '0029_rename_time_of_interenst_end_record_time_of_interest_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detectorcalib',
            name='date',
        ),
        migrations.AddField(
            model_name='detectorcalib',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='calibrations', to=settings.AUTH_USER_MODEL),
        ),
    ]
