# Generated by Django 4.2.11 on 2024-04-08 22:16

import DOSPORTAL.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DOSPORTAL', '0030_remove_detectorcalib_date_detectorcalib_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='name',
            field=models.CharField(default='Record', help_text='Name of this record. Short and simple description of record.', max_length=80, null=True, verbose_name='Record name'),
        ),
        migrations.AlterField(
            model_name='detector',
            name='calib',
            field=models.ManyToManyField(blank=True, help_text='Detector calibration', related_name='detectors', to='DOSPORTAL.detectorcalib'),
        ),
        migrations.AlterField(
            model_name='record',
            name='belongs',
            field=models.ForeignKey(help_text='Organization, which owns this record. If you are the only owner, please leave this field empty.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='records_owning', to='DOSPORTAL.organization'),
        ),
        migrations.AlterField(
            model_name='record',
            name='data_policy',
            field=models.CharField(choices=[('PR', 'Private'), ('PU', 'Public'), ('NV', 'Non-public')], default='PU', help_text='Data policy of this record. Field can be overridden depending by setting of the organisation, that owns this record.', max_length=2),
        ),
        migrations.AlterField(
            model_name='record',
            name='log_file',
            field=models.FileField(blank=True, help_text='Upload recorded data file form your detector', upload_to=DOSPORTAL.models.Record.user_directory_path, verbose_name='File log'),
        ),
        migrations.AlterField(
            model_name='record',
            name='time_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2000, 1, 1, 0, 0), help_text="When 'time is tracked', you can set start time of the record beginning. ", null=True, verbose_name='Measurement beginning time'),
        ),
        migrations.AlterField(
            model_name='record',
            name='time_tracked',
            field=models.BooleanField(default=False, help_text='Tick this box if the record is dependent on absolute time. When you need align record to real time.', verbose_name='Is time tracked?'),
        ),
    ]
