# Generated by Django 4.2.7 on 2023-12-03 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOSPORTAL', '0031_detectorlogbook_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='detector',
            name='data',
            field=models.JSONField(default={}, help_text='Detector metadata, used for advanced data processing and maintaining', verbose_name='Detector data'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detectorlogbook',
            name='public',
            field=models.BooleanField(default=True, help_text='Private logbook will be visible for maintainers of detector and for dosportal admins.', verbose_name='Wish to be visible to everyone?'),
        ),
        migrations.AlterField(
            model_name='detectorlogbook',
            name='text',
            field=models.TextField(help_text='Detailed description of activity made on the detector.', verbose_name='Logbook text'),
        ),
    ]
