# Generated by Django 4.2.11 on 2024-04-09 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DOSPORTAL', '0031_record_name_alter_detector_calib_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='time_of_interest_end',
        ),
        migrations.RemoveField(
            model_name='record',
            name='time_of_interest_start',
        ),
    ]
