# Generated by Django 4.2.7 on 2023-12-03 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOSPORTAL', '0032_detector_data_alter_detectorlogbook_public_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detector',
            name='manufactured_date',
            field=models.DateField(blank=True, help_text='Date when detector was manufactured', null=True, verbose_name='Manufactured date'),
        ),
    ]
