# Generated by Django 4.2.11 on 2024-04-09 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOSPORTAL', '0032_remove_record_time_of_interest_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='time_of_interest_end',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Time of interest end'),
        ),
        migrations.AddField(
            model_name='record',
            name='time_of_interest_start',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='Time of interest start'),
        ),
    ]
