# Generated by Django 4.2.7 on 2023-12-03 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOSPORTAL', '0033_detector_manufactured_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='metadata',
            field=models.JSONField(help_text='record metadata, used for advanced data processing and maintaining', null=True, verbose_name='record_metadata'),
        ),
        migrations.AlterField(
            model_name='detector',
            name='data',
            field=models.JSONField(help_text='Detector metadata, used for advanced data processing and maintaining', verbose_name='Detector metadata'),
        ),
    ]
