# Generated by Django 4.2.11 on 2024-04-11 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOSPORTAL', '0033_record_time_of_interest_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detector',
            name='data',
            field=models.JSONField(blank=True, default=dict, help_text='Detector metadata, used for advanced data processing and maintaining', verbose_name='Detector metadata'),
        ),
        migrations.AlterField(
            model_name='record',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='record metadata, used for advanced data processing and maintaining', verbose_name='record_metadata'),
        ),
    ]
