# Generated by Django 6.0 on 2026-01-05 17:07

import DOSPORTAL.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOSPORTAL', '0035_record_time_internal_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='data_file',
            field=models.FileField(blank=True, help_text='Processed spectral file', null=True, upload_to=DOSPORTAL.models.Record.user_directory_path_data, validators=[DOSPORTAL.models._validate_data_file], verbose_name='Log file'),
        ),
        migrations.AlterField(
            model_name='record',
            name='log_file',
            field=models.FileField(blank=True, help_text='Upload recorded data file form your detector', upload_to=DOSPORTAL.models.Record.user_directory_path, validators=[DOSPORTAL.models._validate_log_file], verbose_name='File log'),
        ),
        migrations.AlterField(
            model_name='record',
            name='metadata_file',
            field=models.FileField(blank=True, help_text='Processed metadata file', null=True, upload_to=DOSPORTAL.models.Record.user_directory_path_data, validators=[DOSPORTAL.models._validate_metadata_file], verbose_name='Metadata file'),
        ),
    ]
