# Generated by Django 6.0 on 2026-01-05 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOSPORTAL', '0036_alter_record_data_file_alter_record_log_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detectorlogbook',
            options={'ordering': ['-created']},
        ),
        migrations.RemoveField(
            model_name='record',
            name='data_policy',
        ),
        migrations.AddField(
            model_name='detectorlogbook',
            name='entry_type',
            field=models.CharField(choices=[('reset', 'Reset'), ('sync', 'Sync'), ('maintenance', 'Maintenance'), ('note', 'Note'), ('location_update', 'Location update'), ('calibration', 'Calibration'), ('other', 'Other')], default='note', help_text='Category of the logbook entry.', max_length=30),
        ),
        migrations.AddField(
            model_name='detectorlogbook',
            name='source',
            field=models.CharField(choices=[('web', 'Web'), ('api', 'API'), ('qr', 'QR'), ('auto', 'Automatic'), ('other', 'Other')], default='web', help_text='Origin of the logbook entry.', max_length=20),
        ),
        migrations.AlterField(
            model_name='record',
            name='belongs',
            field=models.ForeignKey(choices=[('PR', 'Private'), ('PU', 'Public'), ('NV', 'Non-public')], default='PU', help_text='Data policy of this record. Field can be overridden depending by setting of the organisation, that owns this record.', max_length=2, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='records_owning', to='DOSPORTAL.organization'),
        ),
    ]
