# Generated by Django 6.0 on 2026-01-06 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOSPORTAL', '0037_alter_detectorlogbook_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectorlogbook',
            name='altitude',
            field=models.FloatField(blank=True, help_text='Altitude of the location in meters', null=True, verbose_name='Altitude'),
        ),
        migrations.AddField(
            model_name='detectorlogbook',
            name='latitude',
            field=models.FloatField(blank=True, help_text='GPS latitude of the location', null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='detectorlogbook',
            name='longitude',
            field=models.FloatField(blank=True, help_text='GPS longitude of the location', null=True, verbose_name='Longitude'),
        ),
    ]
