# Generated by Django 6.0.1 on 2026-01-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DOSPORTAL', '0039_detectorlogbook_modified_detectorlogbook_modified_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectorlogbook',
            name='location_text',
            field=models.CharField(blank=True, help_text="Location description in text format (e.g., '49.8175, 15.4730' or address)", max_length=255, null=True, verbose_name='Location (text)'),
        ),
    ]
