/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * DOSPORTAL API
 * API Documentation for DOSPORTAL
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  LoginRequestRequest,
  LoginResponse,
  OrganizationSummary,
  OrganizationUser,
  SignupRequestRequest,
  SignupResponse,
  UserProfile,
  UserProfileRequest
} from '.././model';





/**
 * Authenticate user and return authentication token
 */
export const loginCreate = (
    loginRequestRequest: LoginRequestRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<LoginResponse>> => {
    
    
    return axios.default.post(
      `/api/login/`,
      loginRequestRequest,options
    );
  }



export const getLoginCreateMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof loginCreate>>, TError,{data: LoginRequestRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof loginCreate>>, TError,{data: LoginRequestRequest}, TContext> => {

const mutationKey = ['loginCreate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof loginCreate>>, {data: LoginRequestRequest}> = (props) => {
          const {data} = props ?? {};

          return  loginCreate(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type LoginCreateMutationResult = NonNullable<Awaited<ReturnType<typeof loginCreate>>>
    export type LoginCreateMutationBody = LoginRequestRequest
    export type LoginCreateMutationError = AxiosError<unknown>

    export const useLoginCreate = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof loginCreate>>, TError,{data: LoginRequestRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof loginCreate>>,
        TError,
        {data: LoginRequestRequest},
        TContext
      > => {

      const mutationOptions = getLoginCreateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * API logout endpoint. Delete the token.
 */
export const logoutCreate = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.post(
      `/api/logout/`,undefined,options
    );
  }



export const getLogoutCreateMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof logoutCreate>>, TError,void, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof logoutCreate>>, TError,void, TContext> => {

const mutationKey = ['logoutCreate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof logoutCreate>>, void> = () => {
          

          return  logoutCreate(axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type LogoutCreateMutationResult = NonNullable<Awaited<ReturnType<typeof logoutCreate>>>
    
    export type LogoutCreateMutationError = AxiosError<unknown>

    export const useLogoutCreate = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof logoutCreate>>, TError,void, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof logoutCreate>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getLogoutCreateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Create a new user account
 */
export const signupCreate = (
    signupRequestRequest: SignupRequestRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<SignupResponse>> => {
    
    
    return axios.default.post(
      `/api/signup/`,
      signupRequestRequest,options
    );
  }



export const getSignupCreateMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof signupCreate>>, TError,{data: SignupRequestRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof signupCreate>>, TError,{data: SignupRequestRequest}, TContext> => {

const mutationKey = ['signupCreate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof signupCreate>>, {data: SignupRequestRequest}> = (props) => {
          const {data} = props ?? {};

          return  signupCreate(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type SignupCreateMutationResult = NonNullable<Awaited<ReturnType<typeof signupCreate>>>
    export type SignupCreateMutationBody = SignupRequestRequest
    export type SignupCreateMutationError = AxiosError<unknown>

    export const useSignupCreate = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof signupCreate>>, TError,{data: SignupRequestRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof signupCreate>>,
        TError,
        {data: SignupRequestRequest},
        TContext
      > => {

      const mutationOptions = getSignupCreateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    /**
 * Get all organizations that the current user is a member of
 */
export const userOrganizationsList = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<OrganizationUser[]>> => {
    
    
    return axios.default.get(
      `/api/user/organizations/`,options
    );
  }




export const getUserOrganizationsListQueryKey = () => {
    return [
    `/api/user/organizations/`
    ] as const;
    }

    
export const getUserOrganizationsListQueryOptions = <TData = Awaited<ReturnType<typeof userOrganizationsList>>, TError = AxiosError<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof userOrganizationsList>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUserOrganizationsListQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof userOrganizationsList>>> = ({ signal }) => userOrganizationsList({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof userOrganizationsList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UserOrganizationsListQueryResult = NonNullable<Awaited<ReturnType<typeof userOrganizationsList>>>
export type UserOrganizationsListQueryError = AxiosError<unknown>


export function useUserOrganizationsList<TData = Awaited<ReturnType<typeof userOrganizationsList>>, TError = AxiosError<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof userOrganizationsList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof userOrganizationsList>>,
          TError,
          Awaited<ReturnType<typeof userOrganizationsList>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUserOrganizationsList<TData = Awaited<ReturnType<typeof userOrganizationsList>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof userOrganizationsList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof userOrganizationsList>>,
          TError,
          Awaited<ReturnType<typeof userOrganizationsList>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUserOrganizationsList<TData = Awaited<ReturnType<typeof userOrganizationsList>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof userOrganizationsList>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useUserOrganizationsList<TData = Awaited<ReturnType<typeof userOrganizationsList>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof userOrganizationsList>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getUserOrganizationsListQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Get all organizations where the current user is Admin or Owner
 */
export const userOrganizationsOwnedList = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<OrganizationSummary[]>> => {
    
    
    return axios.default.get(
      `/api/user/organizations/owned/`,options
    );
  }




export const getUserOrganizationsOwnedListQueryKey = () => {
    return [
    `/api/user/organizations/owned/`
    ] as const;
    }

    
export const getUserOrganizationsOwnedListQueryOptions = <TData = Awaited<ReturnType<typeof userOrganizationsOwnedList>>, TError = AxiosError<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof userOrganizationsOwnedList>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUserOrganizationsOwnedListQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof userOrganizationsOwnedList>>> = ({ signal }) => userOrganizationsOwnedList({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof userOrganizationsOwnedList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UserOrganizationsOwnedListQueryResult = NonNullable<Awaited<ReturnType<typeof userOrganizationsOwnedList>>>
export type UserOrganizationsOwnedListQueryError = AxiosError<unknown>


export function useUserOrganizationsOwnedList<TData = Awaited<ReturnType<typeof userOrganizationsOwnedList>>, TError = AxiosError<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof userOrganizationsOwnedList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof userOrganizationsOwnedList>>,
          TError,
          Awaited<ReturnType<typeof userOrganizationsOwnedList>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUserOrganizationsOwnedList<TData = Awaited<ReturnType<typeof userOrganizationsOwnedList>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof userOrganizationsOwnedList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof userOrganizationsOwnedList>>,
          TError,
          Awaited<ReturnType<typeof userOrganizationsOwnedList>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUserOrganizationsOwnedList<TData = Awaited<ReturnType<typeof userOrganizationsOwnedList>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof userOrganizationsOwnedList>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useUserOrganizationsOwnedList<TData = Awaited<ReturnType<typeof userOrganizationsOwnedList>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof userOrganizationsOwnedList>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getUserOrganizationsOwnedListQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Get or update current user profile information
 */
export const userProfileRetrieve = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UserProfile>> => {
    
    
    return axios.default.get(
      `/api/user/profile/`,options
    );
  }




export const getUserProfileRetrieveQueryKey = () => {
    return [
    `/api/user/profile/`
    ] as const;
    }

    
export const getUserProfileRetrieveQueryOptions = <TData = Awaited<ReturnType<typeof userProfileRetrieve>>, TError = AxiosError<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof userProfileRetrieve>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUserProfileRetrieveQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof userProfileRetrieve>>> = ({ signal }) => userProfileRetrieve({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof userProfileRetrieve>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UserProfileRetrieveQueryResult = NonNullable<Awaited<ReturnType<typeof userProfileRetrieve>>>
export type UserProfileRetrieveQueryError = AxiosError<unknown>


export function useUserProfileRetrieve<TData = Awaited<ReturnType<typeof userProfileRetrieve>>, TError = AxiosError<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof userProfileRetrieve>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof userProfileRetrieve>>,
          TError,
          Awaited<ReturnType<typeof userProfileRetrieve>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUserProfileRetrieve<TData = Awaited<ReturnType<typeof userProfileRetrieve>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof userProfileRetrieve>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof userProfileRetrieve>>,
          TError,
          Awaited<ReturnType<typeof userProfileRetrieve>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUserProfileRetrieve<TData = Awaited<ReturnType<typeof userProfileRetrieve>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof userProfileRetrieve>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useUserProfileRetrieve<TData = Awaited<ReturnType<typeof userProfileRetrieve>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof userProfileRetrieve>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getUserProfileRetrieveQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Get or update current user profile information
 */
export const userProfileUpdate = (
    userProfileRequest: UserProfileRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UserProfile>> => {
    
    
    return axios.default.put(
      `/api/user/profile/`,
      userProfileRequest,options
    );
  }



export const getUserProfileUpdateMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof userProfileUpdate>>, TError,{data: UserProfileRequest}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof userProfileUpdate>>, TError,{data: UserProfileRequest}, TContext> => {

const mutationKey = ['userProfileUpdate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof userProfileUpdate>>, {data: UserProfileRequest}> = (props) => {
          const {data} = props ?? {};

          return  userProfileUpdate(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UserProfileUpdateMutationResult = NonNullable<Awaited<ReturnType<typeof userProfileUpdate>>>
    export type UserProfileUpdateMutationBody = UserProfileRequest
    export type UserProfileUpdateMutationError = AxiosError<unknown>

    export const useUserProfileUpdate = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof userProfileUpdate>>, TError,{data: UserProfileRequest}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof userProfileUpdate>>,
        TError,
        {data: UserProfileRequest},
        TContext
      > => {

      const mutationOptions = getUserProfileUpdateMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    